StackExchange.Redis.Tests/Keys.cs, StackExchange.Redis/StackExchange/Redis/RedisKey.cs
We've got some code that routinely concats an arbitrary string to a fixed prefix.  It'd be nice to not have to allocate a whole new `string` (or `byte[]`, or whatever) when we're just gonna turn this into a `RedisKey` and be done with it.
This commit exposes the already existing [`WithPrefix`](https://github.com/StackExchange/StackExchange.Redis/blob/d994b7ad57a76586487cd2d460d55cb850498448/StackExchange.Redis/StackExchange/Redis/RedisKey.cs#L253) method on `RedisKey` in separate `Prepend` and `Append` wrapper methods.
=> expose Prepend and Append methods on RedisKey, so we can avoid some string concats in common cases

StackExchange.Redis.Tests/ConnectToUnexistingHost.cs, StackExchange.Redis.Tests/StackExchange.Redis.Tests.csproj, StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs, StackExchange.Redis/StackExchange/Redis/SocketManager.cs
- fixed hardcoded completion type in `SocketManager.BeginConnect` (forced Sync completion type in #113  by mistake). Both successful and failed connections should now be handled as fast as in 1.0.333.
- connect timeout exception type changed to `RedisConnectionException` (for consistency with non/timeout connection errors) .
- forced async execution of `ReconfigureAsync` call from Connect (although `ReconfigureAsync` returns Task is wasn't executed asynchronously because `Connect` was not marked as async. So `task.Wait` call in Connect was always executed after the `ReconfigureAsync` completion, making that timeout ineffective).
=> Fixed connect timeout handling in ConnectionMultiplexer.Connect

StackExchange.Redis.Tests/ConnectingFailDetection.cs, StackExchange.Redis/StackExchange/Redis/DebuggingAids.cs, StackExchange.Redis/StackExchange/Redis/PhysicalBridge.cs, StackExchange.Redis/StackExchange/Redis/PhysicalConnection.cs, StackExchange.Redis/StackExchange/Redis/SocketManager.Poll.cs, StackExchange.Redis/StackExchange/Redis/SocketManager.cs
Fixed #124 - added check to detect azure-specific disconnection type. 
I used a SyncTimeout as a read-write threshold. Maybe this check needs a separate timeout settings?
=> Azure stale connection detection

StackExchange.Redis/StackExchange/Redis/PhysicalConnection.cs
Read callback (in SSL mode) may throw exception if connection is disposed. User code cannot catch and handle this exception resulting in process being terminated. This fix resolved the issue.
Below is the example stack we observed. We also observed NullReferenceException (depending on the timing), 
Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
at System.Net.Security.SslState.CheckThrow(Boolean authSucessCheck)
at System.Net.Security.SslStream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
at StackExchange.Redis.PhysicalConnection.BeginReading()
at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
at System.Net.Security._SslStream.ProcessFrameBody(Int32 readBytes, …
=> Unhandled exception in callback when connection is disposed

StackExchange.Redis/StackExchange/Redis/RedisDatabase.cs
StackExchange.Redis "optimizes" all Lua scripts by preloading them and executing by hash. This fix allows to execute Lua scripts as is through the EVAL when SCRIPT command is not supported. Without this fix you can't run any Lua script with twemproxy.
=> Prevent EVAL to SCRIPT conversion if it is not supported 

StackExchange.Redis.Tests/Expiry.cs, StackExchange.Redis/StackExchange/Redis/RedisDatabase.cs
Fixed Issue #157 KeyExpire's DateTime expiry is affected by LocalTime and test case failed
This pullRequest changed KeyExpiry's DateTime to `when.ToUniversalTime()` and if UnitTest in utc = false create Tokyo(UTC+9:00) local time.
=> fix keyExpiry's DateTime convert to Utc

MigratedBookSleeveTestSuite/Hashes.cs, StackExchange.Redis/StackExchange/Redis/RedisValue.cs
Simple reorder of static field init order fixes this issue.
=> Issue #111: HashSet with RedisValue.EmptyString do not work as ""

StackExchange.Redis.Tests/Issues/DefaultDatabase.cs, StackExchange.Redis.Tests/StackExchange.Redis.Tests.csproj, StackExchange.Redis/StackExchange/Redis/ConfigurationOptions.cs, StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs
I believe there is value in being able to specify the default database ID within the connection string. It falls back to zero if left unspecified.
=> Added a way to specify the default database in the connection string

StackExchange.Redis/StackExchange/Redis/RedisDatabase.cs
`StringGet` and `StringGetAsync` does not check that the passed `keys` array is null or empty.
Empty arrays cause RedisServerException (ERR wrong number of arguments for 'mget' command), while null arrays cause NullReferenceException.
This PR fixes these problems.
=> Add validation to StringGet and StringGetAsync

Docs/Scripting.md, README.md
Very basic documentation I didn't write as part of #170 for scripting, and adds links to the README.md to both Scripting and Profiling documentation.
=> Update documentation for Scripting and Profiling

StackExchange.Redis.Tests/SSL.cs, StackExchange.Redis/StackExchange/Redis/ConfigurationOptions.cs
In clustering mode currently, ClusterConfiguration for every server endpoint is built using the output of "CLUSTER NODES" command which consists of IP addresses of the nodes inside the cluster (SetClusterConfiguration and UpdateClusterRange methods)
However, when we try to authenticate the client to the ssl endpoint, inside SocketMode ISocketCallback.Connected, using the ssl.AuthenticateAsClient method it throws an exception
"The remote certificate is invalid according to the validation procedure” since we are trying to authenticate using the IP address as opposed to the Dns Host name.
An existing workaround this problem is to configure "SslHost" explictly inside the connection string or specify it inside ConfigurationOptions.
However if the users of the client do not configure this …
=> Default SslHost in clustering mode

StackExchange.Redis/StackExchange/Redis/PhysicalConnection.cs, StackExchange.Redis/StackExchange/Redis/RedisTransaction.cs
When multiple clients are trying to modify the same key in a transaction, Redis server returns null response *-1\r\n causing it to throw an “Unexpected response to EXEC: MultiBulk: 0” exception during transaction.ExecuteAsync()."
The fix is to consider *-1\r\n as a null array instead of empty array.
=> StackExchange.Redis to consider separately Response Array as either NULL  or an Empty Array

StackExchange.Redis/StackExchange/Redis/ServerSelectionStrategy.cs
The client was selecting in a wrong way the server endpoint to resend the command, therefore it was failing and propagating the MOVED exception. 
I have noticed that although it was rearranging well the map of servers and hashSlots, if the flag was CommandFlags.DemandMaster and server.IsSelectable(command) returned true then it was selecting null instead selecting the server endpoint itself which was fulfilling the condition needed. Something similar was happening with the other flags.
By exchanging those operands the client is able to select correctly the server to which it will resend the command issued and there is no more MOVED exceptions.
=> #248 Exchanging operands in the ternary operators of server selection in TryResend in ServerSelectionStrategy

StackExchange.Redis/StackExchange/Redis/Format.cs
Redis (v2.8 and v3) returns "inf" for positive infinity values, but here a "+inf" is expected. So changed the code to work with both: "+inf" as well as "inf".
See Issue #287: https://github.com/StackExchange/StackExchange.Redis/issues/287
=> Handle "inf" as well as "+inf"

StackExchange.Redis/StackExchange/Redis/ClusterConfiguration.cs
When hosting a redis cluster deployment on cloud environments where machines get reimaged or reassigned frequently, the CLUSTER NODES output might contain nodes with no endpoint address or multiple nodes assigned to the same endpoint address. These commits add resilience to this state by ignore nodes with no address and adding resilience to duplicate endpoints.
=> Add resilience to non ideal cluster topology in CLUSTER NODES response parsing

StackExchange.Redis/StackExchange/Redis/RedisValue.cs
This fixes the non-CoreClr version of the GetTypeCode() extension method.
=> GetTypeCode() extension method bug fix

StackExchange.Redis/StackExchange/Redis/Message.cs
Attempting to address #237, #275, #205.  I believe @bencican called out the root cause in #237, which is the multiple completions of same the PING message in `PhysicalBridge.OnDisconnected`.  The `PhysicalBridge` code is a bit too unfamiliar to me and it felt safer/more future proof to guard against this within `Message.TryComplete`.  
#275 has a sample unit test that I was using to check this fix, results looked good.  Not sure if we should lock the `resultBox` in case of concurrent calls to `Message.TryComplete`.
=> Ensure Message.resultBox is nulled after successful async TryComplete

StackExchange.Redis/StackExchange/Redis/RedisValue.cs
The comment was indicating the reverse of what `operator bool` is doing.
=> Correct the bool operator comment

StackExchange.Redis/StackExchange/Redis/ClusterConfiguration.cs
Unconfigured cluster nodes might report themselves as endpoint ":{port}",
hence the origin fallback value to make sure that we can address them
=> Fix cluster configuration regressions from 6b317395ace23c4b1018de638de586061547e22b

MigratedBookSleeveTestSuite/Config.cs, StackExchange.Redis/StackExchange/Redis/ConfigurationOptions.cs
The Microsoft Azure team is requesting that AbortConnectOnFailure be false by default at least for Azure endpoints.
=> Set AbortConnectOnFailure to false for Azure

StackExchange.Redis/StackExchange/Redis/IDatabase.cs, StackExchange.Redis/StackExchange/Redis/IDatabaseAsync.cs
The comments for these two functions was incorrectly stating that start and stop were 0-based indexes for fetching a fixed number of items. ZRANGEBYSCORE actually takes a min and max value which create a range which an unknown amount of members may qualify.
I think the method arguments should be changed to min / max to be more semantic and match actual Redis documentation, but this would require changes to implementation and might be breaking.
=> Update summary comments for SortedSetRangeByScore and SortedSetRangeByScoreWithScores

StackExchange.Redis/StackExchange/Redis/ConfigurationOptions.cs, StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs
ResponseTimeout is set as default to synctimeout. A higher responseTime would have adverse side effect on quickly reconnecting a mux in case of a network blip.
=> proposing to change back SE.REdis synctimeout to be 1 second 

StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs
So I ran into this issue as well. After reading through some of the comments and taking a look at the code, I noticed an unnecessary indirection in `ConnectionMultiPlexer.ConnectImpl` which appears to be causing a deadlock:
```
// note that task has timeouts internally, so it might take *just over* the regular timeout
// wrap into task to force async execution
var task = Factory.StartNew(() => muxer.ReconfigureAsync(true, false, log, null, "connect").Result);
```
What's happening here is the code is spawning an async task which waits _synchronously_ on an async task result. This is bad juju. What it appears is happening next is the code blocks the context thread waiting for the wrapper task created with `Factory.StartNew` to return:
```
if (!task.Wait(muxer.SyncConnectTimeout(true)))
``` …
=> Remove indirection to mitigate a presumed deadlock. Fixes StackExchange/StackExchange.Redis#42.

Docs/Basics.md
I wasn't sure if `too` was supposed to be `tool` and was a typo, or if `too` was deliberate.  Regardless, it sounded weird to me and I think this is clearer.
=> reworded redis pub/sub doc to be more readable

StackExchange.Redis.Tests/ConnectionFailedErrors.cs, StackExchange.Redis.Tests/ExceptionFactoryTests.cs, StackExchange.Redis.Tests/TestBase.cs, StackExchange.Redis/StackExchange/Redis/ConnectionFailureType.cs, StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs, StackExchange.Redis/StackExchange/Redis/ExceptionFactory.cs, StackExchange.Redis/StackExchange/Redis/PhysicalBridge.cs, StackExchange.Redis/StackExchange/Redis/PhysicalConnection.cs, StackExchange.Redis/StackExchange/Redis/RedisBatch.cs, StackExchange.Redis/StackExchange/Redis/RedisServer.cs, StackExchange.Redis/StackExchange/Redis/ResultProcessor.cs, StackExchange.Redis/StackExchange/Redis/ServerEndPoint.cs
Currently there is not an easy way to understand from the RedisConnectionException thrown for the root cause of an error.
for example, for certification validation failure, it doesn't give any details about the error.
This pull request is help surface the exception from Serverendpoints as an innerexception of 
RedisConnectionException which would further help a user in investigating the root cause of an error.
Following are examples of how the exception would look like after this change:
1. Redis cert validation failure
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: GET test 
---> StackExchange.Redis.RedisConnectionException: AuthenticationFailure on *.redis.cache.windows.net:6380/Subscription, origin: Connected, input-buffer: 0, …
=> SE.Redis to surface error from serverendpoint as an innerexception 

StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs, StackExchange.Redis/StackExchange/Redis/DebuggingAids.cs
Capture client system CPU percentage in timeout error messages when possible to help debug timeouts.
=> Capture client system CPU percentage in timeout error messages

MigratedBookSleeveTestSuite/Config.cs, StackExchange.Redis/StackExchange/Redis/ConfigurationOptions.cs, StackExchange.Redis/StackExchange/Redis/RedisFeatures.cs
With default version of 2.0, for a large number of connection to a Redis endpoint features.InfoSections returns false and  causes full info command to be executed during initiation of a multiplexer. 
info command from high number of connections trying to connect,  can be expensive for redis server.
Making default version to 3.0 so that 'info replication' and 'info server' commands are leveraged and improves performance.
=> Set default version to 3.0 for Azure

StackExchange.Redis/StackExchange/Redis/Message.cs, StackExchange.Redis/StackExchange/Redis/MessageQueue.cs, StackExchange.Redis/StackExchange/Redis/PhysicalBridge.cs
Stop PING from being completed twice in disconnect scenario by making PeekPing actually dequeue. Prevent any Message from having its resultBox recycled twice by getting/nulling resultBox in a thread safe way
=> Prevent ResultBox from being recycled twice

StackExchange.Redis/StackExchange/Redis/RedisValue.cs
`RedisValue.TryParseInt64` method throws an overflow exception while parsing `-9223372036854775808` which is a minimum value of long. This PR fixes this bug.
=> Fix overflow in parsing "-9223372036854775808"

StackExchange.Redis.Tests/Config.cs, StackExchange.Redis/StackExchange/Redis/ConfigurationOptions.cs, StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs
helps to identify where a client connection is coming from, further helps to identify any connection related problems.
=> Default ClientName to Roleinstance ID for a web/worker role 

StackExchange.Redis.Tests/Config.cs, StackExchange.Redis.Tests/ConnectionFailedErrors.cs
Looks like this was missed in PR #379 when moving the _TryGetAzureRoleInstanceIdNoThrow_ method from the _ConfigurationOptions_ class to the _ConnectionMultiplexer_ class.
=> Fixed build error caused by TryGetAzureRoleInstanceIdNoThrow test

StackExchange.Redis.Tests/Transactions.cs, StackExchange.Redis/StackExchange/Redis/Condition.cs
For enabling length checks (==, >, <) against a variety of types.
These map to:
String -> STRLEN
List -> LLEN
Set -> SCARD
SortedSet -> ZCARD
Hash -> HLEN
=> Length based conditions for Transactions

Docs/Timeouts.md
You can't set the processModel in the web.config  "The processModel section can be set only within the Machine.config" and is confusing to have here to be web.config
=> Configuring the minIoThreads

StackExchange.Redis/StackExchange/Redis/RedisSubscriber.cs
SUBSCRIBE and PSUBSCRIBE are not write ops and can be
performed on slaved instances, so there's no reason to
explicitly pass DemandMaster when selecting the server.
Instead, use the CommandFlags passed as the parameter to Subscribe()
=> Use the supplied flags when selecting a server to subscribe to

BasicTest/BasicTest.project.json, MigratedBookSleeveTestSuite/MigratedBookSleeveTestSuite.project.json, MigratedBookSleeveTestSuite/packages.config
Visual Studio tooling will use `project.json` to restore nuget dependencies
when it finds one beside .csproj. This change uses more specific
`<project name>.project.json` to specify dependencies.
Connect to #446.
=> Work around build issue for existing csproj's

StackExchange.Redis/StackExchange/Redis/ConfigurationOptions.cs, StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs
ReconfigureAsync in ConnectionMultiplexer.cs logs the configuration string, including the password.
This change addresses the security concern of logging passwords without changing other behavior.
=> Remove password from logging of configuration string.

StackExchange.Redis/StackExchange/Redis/ConfigurationOptions.cs
Spotted this whilst using the library, thought I'd contribute a fix!
The Intellisense documentation for the Proxy Property was the same as AllowAdmin
Probably error through Copy and Paste.
=> Fixing Documentation for ConfigurationOptions.Proxy

StackExchange.Redis.Tests/ConnectionReconnectRetryPolicyTests.cs, StackExchange.Redis/StackExchange/Redis/ConfigurationOptions.cs, StackExchange.Redis/StackExchange/Redis/ExponentialRetry.cs, StackExchange.Redis/StackExchange/Redis/IReconnectRetryPolicy.cs, StackExchange.Redis/StackExchange/Redis/LinearRetry.cs, StackExchange.Redis/StackExchange/Redis/PhysicalBridge.cs
Implemented reconnect retry policies to back off connectimeout wait time linearly (default) or exponentially
config.ReconnectRetryPolicy = new ExponentialRetry(config.ConnectTimeout);
Looking for code review and any other feedback on the pull request.
thx.
=> SE.Redis Reconnect retry policy

README.md
The "booksleeve" project was moved to the archive directory in google code. I updated the new link for the "booksleeve" reference.
=> Updating link to the "booksleeve" project in ReadeMe file.

StackExchange.Redis.Tests/ConnectionFailedErrors.cs, StackExchange.Redis/StackExchange/Redis/CommandStatus.cs, StackExchange.Redis/StackExchange/Redis/ExceptionFactory.cs, StackExchange.Redis/StackExchange/Redis/Message.cs
I would like to get feedback on this proposal, where client application can read status of a command and to be able to retry if it was never sent over the wire. 
```c#
var policy = Policy.Handle<RedisTimeoutException>(p=> p.Commandstatus == CommandStatus.WaitingToBeSentToRedis)
.Or<RedisConnectionException>(p=> p.CommandStatus == CommandStatus.WaitingToBeSentToRedis)
.Retry(3,(exception, retrycount) =>
{
//log("Try {0} failed with {1}", retrycount, exception);
});
try
{
policy.Execute(() => conn.GetDatabase().StringGet("test"));
}
catch (Exception e)
{ 
//log
}
```
=> supporting status for being able to retry, if command was never sent over the wire.

Docs/Configuration.md, MigratedBookSleeveTestSuite/Config.cs, StackExchange.Redis/StackExchange/Redis/ConfigurationOptions.cs, StackExchange.Redis/StackExchange/Redis/ExtensionMethods.cs, StackExchange.Redis/StackExchange/Redis/PhysicalConnection.cs
This property allows you to configure the list of acceptable SSL/TLS Protocols for encrypted communication.  Without this setting, users are required to make changes to machine wide settings, which can break other applications that are not compatible.
=> Add SslProtocols property to ConfigurationOptions

docs/Timeouts.md
Fixed the URL to the properties of <processModel in machine.web, added a comment regarding using the value in web.config (it's not possible)
=> Update URL for the processModel reference

StackExchange.Redis/StackExchange/Redis/RawResult.cs
Fixed the return of methods GetItemsAsGeoPosition and GetItemsAsGeoPositionArray on RawResult.cs, now these methods respect the constructor of GeoPosition obj.
=> Issue 690 - Error at GeoPosition

StackExchange.Redis/StackExchange/Redis/SocketManager.cs
This should allow us to use ipv6 based hosts and endpoints. Closes #252
=> feat: use endpoint address family instead of hardcoded InterNetwork

StackExchange.Redis/StackExchange/Redis/PhysicalConnection.cs
It was unreachable because EndOfStreamException is inherited from IOException.
=> Set SocketClosed on EndOfStreamException.

Directory.build.props, StackExchange.Redis.Tests/Profiling.cs, StackExchange.Redis.Tests/StackExchange.Redis.Tests.csproj, StackExchange.Redis/StackExchange/Redis/PhysicalBridge.cs, StackExchange.Redis/StackExchange/Redis/ProfileStorage.cs
Hopefully solves #280. 
For `IMultiMessage`:s, such as a `ScriptEvalMessage`, `SetRequestSent` was called twice, which triggered an exception in `ProfileStorage`. The exception is weirdly rethrown as `UnableToResolvePhysicalConnection`.
Possible solutions:
1. Don't throw the exception in `ProfileStorage`
2. Detect in `Message.SetRequestSent` if the message was already sent, and don't forward the call to  `ProfileStorage` if it was.
3. Detect in `PhysicalBridge` whether the `IMultiMessage` instance was returned from `GetMessages` and ignore the extra call to `SetRequestSent` if it was.
I chose solution 3, since it scoped the change to `IMultiMessage`:s, but the other solutions should work equally fine. If it's really regarded as an error to call `SetRequestSent` twice, I think the …
=> Removed invalid call to SetRequestSent for IMultiMessage

StackExchange.Redis.Tests/Issues/Issue791.cs, StackExchange.Redis/StackExchange/Redis/ConfigurationOptions.cs, StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs
Currently **ConnectionMultiplexer.PreserveAsyncOrder** can be changed by the property only.
Add **PreserveAsyncOrder** property  to **ConfigurationOptions** and make **ConfigurationOptions .Parse** method to parse it from connection string. It could look like this:
```
"contoso.redis.cache.windows.net,abortConnect=true, preserveAsyncOrder=true"
```
#791
=> Support PreserveAsyncOrder in connection string

Directory.build.props, StackExchange.Redis.Tests/Helpers/Attributes.cs, StackExchange.Redis.Tests/StackExchange.Redis.Tests.csproj, StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs
This prevents calling TryGetAzureRoleInstanceIdNoThrow() repeatedly in the null
case.
=> Give defaultClientName a value when it is null

StackExchange.Redis.Tests/TaskTests.cs, StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs, StackExchange.Redis/StackExchange/Redis/RedisBatch.cs, StackExchange.Redis/StackExchange/Redis/RedisTransaction.cs, StackExchange.Redis/StackExchange/Redis/ServerEndPoint.cs, StackExchange.Redis/StackExchange/Redis/TaskSource.cs
After 50547eba453ff42b7b1b965f3f710dfcb177ca98, TaskSource.Create and TaskSource.CreateDenyExecSync methods are the same. There was some crud left everywhere that appeared like differences but it's really determined once in the static initializer for TaskSource based on the platform anyway.
I've fixed the tests as well - they were a bit backwards on logic/assumptions so hard to read, and have been failing for some time. Now we'd expect ContinueWithExecSync to *not* be hijacked, and everything else to be...that's how the tests are as well.
Note: the #if DEBUG change is because internals are already visible to tests...just simpler.
cc @mgravell for eyes - I've tested and running cross-platform. This is part of an overall effort to get tests green and cleanup in prep for network rewrite.
=> Remove TaskSource.CreateDenyExecSync

docs/Timeouts.md
Example of setting ```minIoThreads``` configuration option for ASP.NET was not shown correctly.
=> Corrected formatting in docs/Timeouts.md

StackExchange.Redis/StackExchange/Redis/Interfaces/IDatabase.cs, StackExchange.Redis/StackExchange/Redis/Interfaces/IDatabaseAsync.cs
The documentation for the overload of IDatabaseAsync.HashSetAsync that takes multiple fields/values was somewhat ambiguous. It could have been read to mean that fields not set as a part of the HashSetAsync are deleted rather than preserved. The documentation for HMSET was clearer, so this borrows some of the verbiage from the Redis documentation into the documentation for HashSetAsync.
=> Clarify the documentation for IDatabase(Async).HashSet(Async)

docs/Timeouts.md
The article is about minIoThreads, but example uses maxIoThreads
=> Mistyping in parameter name

StackExchange.Redis/StackExchange/Redis/Exceptions.cs
In unit tests mocking out an IDatabase with implementations that throw
an error was not possible. Constructing the Exception instances wasn't
accessible in user code. It is now.
This fixes #825.
=> Makes Exception constructors public

StackExchange.Redis.Tests/ConnectToUnexistingHost.cs, StackExchange.Redis.Tests/ConnectingFailDetection.cs, StackExchange.Redis.Tests/ConnectionFailedErrors.cs, StackExchange.Redis.Tests/ExceptionFactoryTests.cs, StackExchange.Redis/StackExchange/Redis/DebuggingAids.cs, StackExchange.Redis/StackExchange/Redis/SocketManager.cs
This was an expedition, but here's the history:
- There are 2 forks in the connection logic
- One for Mono (the `DnsEndpoint` split, see #20 and #155)
- One for `.BeginConnect()` and one for `.ConnectAsync()` (because `netstandard1.x` was "async all the things!")
- There's a behind-the-scenes fork on completion type, but for actual library consumers (and not tests), it was always `.Any`, which was effectively `.Sync`.
There was also a critical bug fix in #113 that unfortuantely added a lot of complexity here. The maintenance problem is this complexity wasn't even used, as far as I can tell. It was only ever exposed to even be possibly used in the test project. So we had complicated connection logic, only for the sake of testing it. Unless I'm an idiot, which is entirely possible.
This …
=> Simplify SocketManager.BeginConnect() with not-used-outside-of-tests code removal.

StackExchange.Redis/StackExchange/Redis/SocketManager.cs
.NET Core 2.1 introduced `UnixDomainSocketEndPoint` and it doesn't work with redis client because of 2 things:  
1. `ProtocolType` should be `Unspecified` instead of `Tcp` otherwise Socket constructor throws that it is not supported. [See these tests in corefx repo](https://github.com/dotnet/corefx/blob/b21589f01d699617fb2fba6589af4e43c02d4f31/src/System.Net.Sockets/tests/FunctionalTests/UnixDomainSocketTest.netcoreapp.cs) - they use `ProtocolType.Unspecified`  
2.  `Socket.NoDelay` is not supported by Unix domain sockets - it throws when trying to set it
=> Added support for UnixDomainSocketEndPoint introduced in .NET Core 2.1

StackExchange.Redis.Tests/KeysAndValues.cs, StackExchange.Redis.Tests/RawResultTests.cs, StackExchange.Redis/StackExchange.Redis.csproj, StackExchange.Redis/StackExchange/Redis/DebuggingAids.cs, StackExchange.Redis/StackExchange/Redis/Format.cs, StackExchange.Redis/StackExchange/Redis/LoggingPipe.cs, StackExchange.Redis/StackExchange/Redis/LoggingTextStream.cs, StackExchange.Redis/StackExchange/Redis/PhysicalConnection.cs, StackExchange.Redis/StackExchange/Redis/RawResult.cs, StackExchange.Redis/StackExchange/Redis/RedisDatabase.cs, StackExchange.Redis/StackExchange/Redis/RedisKey.cs, StackExchange.Redis/StackExchange/Redis/RedisResult.cs, StackExchange.Redis/StackExchange/Redis/RedisTransaction.cs, StackExchange.Redis/StackExchange/Redis/RedisValue.cs, StackExchange.Redis/StackExchange/Redis/ResultProcessor.cs, TestConsole/Program.cs, TestConsole/TestConsole.csproj
- refactor internals of `RedisValue` to avoid allocations - don't pre-encode strings, for example
- tweak read/write code of `RedisValue` accordingly
- use `ArrayPool<T>.Shared` for the internals of `RawResult` to avoid allocations
- ensure `RawResult` is recycled on success or failure
=> Redisvalue

StackExchange.Redis.Tests/DatabaseWrapperTests.cs, StackExchange.Redis.Tests/Sets.cs, StackExchange.Redis.Tests/WrapperBaseTests.cs, StackExchange.Redis/StackExchange/Redis/Interfaces/IDatabase.cs, StackExchange.Redis/StackExchange/Redis/Interfaces/IDatabaseAsync.cs, StackExchange.Redis/StackExchange/Redis/KeyspaceIsolation/DatabaseWrapper.cs, StackExchange.Redis/StackExchange/Redis/KeyspaceIsolation/WrapperBase.cs, StackExchange.Redis/StackExchange/Redis/RedisDatabase.cs
This API was missing the newer overload added in Redis 3.2 - resolves #203 for v2.
=> API: Add SetPop/SetPopAsync count overloads

StackExchange.Redis.Tests/FormatTests.cs, StackExchange.Redis.Tests/Performance.cs, StackExchange.Redis/StackExchange/Redis/Format.cs, StackExchange.Redis/StackExchange/Redis/SocketManager.cs
TL;DR: We previously did IP:Port parsing based on splitting at the semicolon...that's pretty hostile for IPv6 and breaks everything. This adopts better parsing from Microsoft.AspNetCore since it doesn't exist in the BCL. The BCL/API conversation is started here: https://github.com/dotnet/corefx/issues/23463
A quick way to test this across all tests is via TestConfig, for example:
```json
{
"MasterServer": "[::1]",
"SlaveServer": "[::1]",
"SecureServer": "[::1]"
}
```
Note: there's still an `Unspecified` == `AddressFamily.InterNetwork` in `SocketManager` which may be affecting DNS endpoints that are v6...need to look at that next. This change allows actually connecting to an IPv6 endpoint via IP though, that's step 1.
cc @mgravell as a heads up this is in-progress
=> Initial IPv6 connection support

StackExchange.Redis/StackExchange/Redis/PhysicalConnection.cs
FIX. All Operation will timeout on SSL connection.
When NetworkStream.BeginRead () throws an IOException, the ConnectionMultiplexer.IsConnected will keep true.
The PhysicalConnection.BeginReading () method is called by the PhysicalConnection.endRead delegate and the SocketManager.EndConnectImpl () method (via the PhysicalConnection.StartReading()).
PhysicalConnection.RecordConnectionFailed() is being handled by catching an exception in these functions.
If the IOException is not thrown again, the caller's disconnection detection is hindered.
And endRead is never called again.
=> fix `PhysicalConnection.BeginReading()` exception handling

StackExchange.Redis/StackExchange/Redis/Interfaces/IServer.cs, StackExchange.Redis/StackExchange/Redis/RedisLiterals.cs, StackExchange.Redis/StackExchange/Redis/RedisServer.cs
1.Node about sentinels 
Sometimes wo need get a redisMaster‘s seninels info,so i add a command sentinels
2.Node about scan
SCAN is a cursor based iterator.Sometime because some reasons we don't need all keys,we just need 
one pageSize keys,and the value of the cursor argument in the next call. So I add a method .
RedisKey[] Keys(ref long refCursor, int database = 0, RedisValue pattern = default(RedisValue), int pageSize = RedisBase.CursorUtils.DefaultPageSize, long cursor = RedisBase.CursorUtils.Origin, int pageOffset = 0, CommandFlags flags = CommandFlags.None);
refCursor is the cursor argument in the next call.
=> add a command sentinels 

Directory.Build.props, Directory.build.props, NRediSearch/NRediSearch.csproj, RedisConfigs/start-all.sh, StackExchange.Redis.Modules/StackExchange.Redis.Modules.csproj, StackExchange.Redis.Server/StackExchange.Redis.Server.csproj, StackExchange.Redis.StrongName/StackExchange.Redis.StrongName.csproj, StackExchange.Redis.Tests/GeoTests.cs, StackExchange.Redis.Tests/RedisFeaturesTests.cs, StackExchange.Redis.Tests/StackExchange.Redis.Tests.csproj, StackExchange.Redis/ConnectionMultiplexer.cs, StackExchange.Redis/ExceptionFactory.cs, StackExchange.Redis/PerfCounterHelper.cs, StackExchange.Redis/ResultProcessor.cs, StackExchange.Redis/StackExchange.Redis.csproj, appveyor.yml
This won't pass yet (some tests are failing on Ubuntu) and it ~1.5x double build times. I'll inquire about paying for concurrent builds Monday to resolve the latter.
But! Those tests are going against the pre-installed Redis 4.0.8 official build instead of redis-64. \o/
What's interesting is right out of the gate it reproduced #913 (protocol error): https://ci.appveyor.com/project/StackExchange/stackexchange-redis/build/2.0.0-alpha.357+g67ded86dd3/tests
=> Build: add Ubuntu

src/StackExchange.Redis/BufferReader.cs, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/ExtensionMethods.cs, src/StackExchange.Redis/StackExchange.Redis.csproj, toys/TestConsole/Program.cs, toys/TestConsole/TestConsole.csproj
giving up on making "vectors" happy; instead, just give up and use black-box knowledge of which code paths touch vectors, and just manually remove those path dependencies via manual fallbacks
=> remove indirect vector usage (on < net472, at least); it breaks the world

README.md
Current link is to the miniprofiler project.
=> Fix project link under build status image

src/StackExchange.Redis/RedisTransaction.cs, src/StackExchange.Redis/ResultBox.cs, src/StackExchange.Redis/TaskSource.cs, tests/StackExchange.Redis.Tests/Transactions.cs, toys/StackExchange.Redis.Server/RespServer.cs
For discussion, see issue #943 
- make transaction inner tasks use `RunContinuationsAsynchronously`
- detect `RunContinuationsAsynchronously` in `ResultBox` completion, and set directly rather than deferred
=> make transaction inner tasks use RunContinuationsAsynchronously

src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/Message.cs, src/StackExchange.Redis/PhysicalBridge.cs, src/StackExchange.Redis/PhysicalConnection.cs, src/StackExchange.Redis/StackExchange.Redis.csproj, tests/BasicTest/Program.cs, toys/TestConsole/Program.cs
by reporting a: what the *offending physical connection was doing* (if we're trying to get the write lock), and b: how much data has flown on the connection while trying to do it (write lock or timeout waiting for response)
cross-reference: #1006
=> improve error reporting (in particular for timeouts)

src/StackExchange.Redis/PhysicalConnection.cs
lastReadTickCount is never updated after the connection is established, which leads to some confusing error messages.
=> Update lastReadTickCount in ReadFromPipe

src/StackExchange.Redis/Enums/RedisCommand.cs, src/StackExchange.Redis/Interfaces/IDatabase.cs, src/StackExchange.Redis/Interfaces/IDatabaseAsync.cs, src/StackExchange.Redis/KeyspaceIsolation/DatabaseWrapper.cs, src/StackExchange.Redis/KeyspaceIsolation/WrapperBase.cs, src/StackExchange.Redis/Message.cs, src/StackExchange.Redis/RedisDatabase.cs, src/StackExchange.Redis/RedisFeatures.cs, src/StackExchange.Redis/ResultProcessor.cs, tests/StackExchange.Redis.Tests/SortedSets.cs
Redis 5.0.0 added functionality for popping from sorted sets, see [ZPOPMIN](https://redis.io/commands/zpopmin) and [ZPOPMAX](https://redis.io/commands/zpopmax).
=> Add pop functionality to sorted set (ZPOPMIN, ZPOPMAX)

src/StackExchange.Redis/ConfigurationOptions.cs, tests/StackExchange.Redis.Tests/Deprecated.cs
Addresses #1029 
Alternatively, is there a recommended way of accomplishing what this used to do in v1?
=> Remove obsolete responseTimeout setting

src/StackExchange.Redis/ChannelMessageQueue.cs, src/StackExchange.Redis/MessageCompletable.cs, src/StackExchange.Redis/RedisSubscriber.cs, src/StackExchange.Redis/StackExchange.Redis.csproj, tests/StackExchange.Redis.Tests/Issues/Issue1101.cs
change how we store and work with pub-sub; previously we had two delegate fields - one for the async callbacks (things we don't trust), and one for the sync callbacks (things we *do* trust) - which means additional delegates even when using just queues, and lots of delegate juggling when adding/removing; additionally, because we can't trust any particular delegate to complete without failing, we make lots of use of `GetInvocationList()`, which allocates a new array each time.
New strategy:
- retain the delegate approach for old-style delegate consumers
- use a new allocation-free API from pipelines-sockets-unofficial to a: check whether delegates are actually single-target (if so, just invoke), and b: iterate them without allocating
- make `ChannelMessageQueue` into a linked-list - no …
=> Rework queues

docs/ReleaseNotes.md, src/StackExchange.Redis/Format.cs, src/StackExchange.Redis/PhysicalConnection.cs, src/StackExchange.Redis/RawResult.cs, src/StackExchange.Redis/RedisDatabase.cs, src/StackExchange.Redis/RedisResult.cs, src/StackExchange.Redis/RedisValue.cs, tests/StackExchange.Redis.Tests/Issues/Issue1103.cs, tests/StackExchange.Redis.Tests/Streams.cs, toys/StackExchange.Redis.Server/TypedRedisValue.cs
context: #1103
This necessitated a new sentinel value for handling very large (64-bit) `ulong`, as we need to encode/decode them differently (obviously, they're not large negative numbers) - but we treat everything up to 63-bit as the previous `long`, for simplicity.
Adding these operators made some of the *other* operators ambiguous (from the compiler's perspective), so additional operators were also added to make this work without complaint.
Additionally:
- some tweaks to remove unnecessary string allocations (by using the `Utf8Parser`) were exploited
- all existing *direct* access to the overloaded field were removed; that was getting dangerous - there are now properties for all of these uses
=> Fix #1103 - add explicit operator support for ulong on RedisValue

docs/Streams.md, docs/index.md
Just doing what I should've done already...
I wasn't an English major so I'm sure there are some grammatical errors. But at least this is a start.
=> Added documentation for the Stream data type.

docs/Basics.md
Including v2 API mentioned in https://github.com/StackExchange/StackExchange.Redis/issues/639 for both synchronous and asynchronous handlers.
=> Expanding pub/sub handler API docs

src/StackExchange.Redis/Profiling/ProfiledCommand.cs, src/StackExchange.Redis/Profiling/TimeSpanHelper.cs
We were using profiling, and our durations were crazy high.
We traced it down to this, the stopwatch can be a high or low resolution.
When constructing the timespan, we should check if the stopwatch was high resolution and do some calculations for a more accurate time.
=> Accurate timespan if the stopwatch is high resolution

docs/Timeouts.md
dedicate_ thread-pool is almost fully available --> dedicated thread-pool is almost fully available
=> misspellind

src/StackExchange.Redis/GeoEntry.cs
It's impossible to mock `GeoRadius` and `GeoRadiusAsync` methods now because `GeoRadiusResult` constructor is internal. Given that constructors for all other GEO calls are public I think it's possible to make `GeoRadiusResult` constructor public as well.
=> Make GeoRadiusResult constructor public to make it mockable

docs/Basics.md
There were two missing parentheses on the Basics docs code. Really minor stuff.
=> Updated Basics.md - Missing parentheses

src/StackExchange.Redis/Enums/RedisCommand.cs, src/StackExchange.Redis/Interfaces/IDatabase.cs, src/StackExchange.Redis/Interfaces/IDatabaseAsync.cs, src/StackExchange.Redis/KeyspaceIsolation/DatabaseWrapper.cs, src/StackExchange.Redis/KeyspaceIsolation/WrapperBase.cs, src/StackExchange.Redis/RedisDatabase.cs, src/StackExchange.Redis/RedisFeatures.cs, tests/StackExchange.Redis.Tests/DatabaseWrapperTests.cs, tests/StackExchange.Redis.Tests/Strings.cs, tests/StackExchange.Redis.Tests/WrapperBaseTests.cs
=> Add HSTRLEN command implementation and testing

docs/PubSubOrder.md
Updated documentation to reflect that PreserveAsyncOrder is deprecated and ChannelMessageQueue should be used instead
=> Updated documentation as PreserveAsyncOrder is deprecated

src/StackExchange.Redis/RedisDatabase.cs, tests/StackExchange.Redis.Tests/Sets.cs
This provides a fix for #1282. I hope the tests are sufficient.
=> fix for #1282: do no-op when adding 0 values to a set

src/StackExchange.Redis/Interfaces/IServer.cs
This PR addresses #1058 by changing the XML documentation in the `IServer` interface to specify the timezone returned by the `Time` and `TimeAsync` methods (UTC) and what to do to get the local time from the value returned from those methods.
=> Extending description of the IServer.Time and IServer.TimeAsync

docs/Testing.md
The previous link was relative to the document, however, when displayed in GitHub Pages it ends in a 404. I've changed to point to the source file in GitHub UI.
=> Fix TestConfig.cs link

RedisConfigs/Sentinel/redis-7010.conf, RedisConfigs/Sentinel/redis-7011.conf, RedisConfigs/Sentinel/sentinel-26379.conf, RedisConfigs/Sentinel/sentinel-26380.conf
These got left behind in root due to being ignored in git, needed a good 'ol `git rm -r --cached RedisConfigs/Sentinel/` here.
=> Cleanup: remove old Sentinel config dupes

.gitignore, Build.csproj, Directory.Build.props, NuGet.Config, StackExchange.Redis.sln, appveyor.yml, build.ps1, global.json, src/Directory.Build.props, src/NRediSearch/NRediSearch.csproj, src/StackExchange.Redis/RedisFeatures.cs, src/StackExchange.Redis/StackExchange.Redis.csproj, tests/BasicTest/BasicTest.csproj, tests/BasicTestBaseline/BasicTestBaseline.csproj, tests/Directory.Build.props, tests/Directory.Build.targets, tests/NRediSearch.Test/Attributes.cs, tests/NRediSearch.Test/NRediSearch.Test.csproj, tests/NRediSearch.Test/RediSearchTestBase.cs, tests/StackExchange.Redis.Tests/StackExchange.Redis.Tests.csproj, toys/StackExchange.Redis.Server/StackExchange.Redis.Server.csproj, toys/TestConsole/TestConsole.csproj, toys/TestConsoleBaseline/TestConsoleBaseline.csproj
Note that we're only building `StackExchange.Redis` and `NRediSearch` in the CI build so this wasn't apparent as an issue, but it's also easily remedied. Cleaning up the xUnit MyGet feed as well since it was an intermittent issue earlier in testing this...and turns out we don't use any betas or need them anymore, so why not simplify anyhow.
Overall, this is a simpler alternative to #1313 and more build simplification/cleanup:
Total changes:
- Moves to 3.x build SDK (just to update)
- Moves to `Visual Studio 2019` AppVeyor build image, for 3.x support (removes need to install SDK)
- Rolls forward to latest version
- Moves to `Build.csproj` for building
- Simplifies `build.ps1`
- Adds `NRediSearch` to the test suite (on Linux in CI, since Windows is against 3.x)
- Adds …
=> Fix builds for all packages on Linux

src/StackExchange.Redis/Condition.cs, tests/StackExchange.Redis.Tests/Transactions.cs
=> Add Condition.SortedSetLengthEqual with min and max score

src/StackExchange.Redis/Enums/RedisCommand.cs, src/StackExchange.Redis/Interfaces/IDatabase.cs, src/StackExchange.Redis/Interfaces/IDatabaseAsync.cs, src/StackExchange.Redis/KeyspaceIsolation/DatabaseWrapper.cs, src/StackExchange.Redis/KeyspaceIsolation/WrapperBase.cs, src/StackExchange.Redis/Message.cs, src/StackExchange.Redis/RedisDatabase.cs, src/StackExchange.Redis/RedisFeatures.cs, tests/StackExchange.Redis.Tests/Keys.cs, tests/StackExchange.Redis.Tests/WrapperBaseTests.cs
=> Add support for TOUCH command 

src/NRediSearch/Query.cs
=> Added "Return" parameter to Query.

src/StackExchange.Redis/ConnectionFailedEventArgs.cs, src/StackExchange.Redis/EndPointEventArgs.cs, src/StackExchange.Redis/HashSlotMovedEventArgs.cs, src/StackExchange.Redis/InternalErrorEventArgs.cs, src/StackExchange.Redis/RedisErrorEventArgs.cs, tests/StackExchange.Redis.Tests/EventArgsTests.cs, tests/StackExchange.Redis.Tests/StackExchange.Redis.Tests.csproj
Create public contructors for StackExchange.Redis event args to be able to create tests scenarios based on redis events. Add sealed attribute to other EventArgs for consistency.
Issue with details - https://github.com/StackExchange/StackExchange.Redis/issues/1325
=> Create public contructors for StackExchange.Redis event args for testing purpose

docs/Timeouts.md
I have been getting Redis Timeout under high load, but it was not making sense at all. So i opened the source to understand what these abbreviations meant. I hope it will help people understand error messages a lot better.
My CPU Use case:
If Redis dedicated thread pool state looks good, and global thread pool has more free threads than minimum threads, but your CPU is usage is 90%, more likely you will face time outs, depending upon the size of bytes client is trying to read or write.
=> Include details of abbreviations seen in exceptions

docs/Configuration.md, src/StackExchange.Redis/ConfigurationOptions.cs, src/StackExchange.Redis/ExtensionMethods.cs, src/StackExchange.Redis/PhysicalConnection.cs
Hello,
in an enterprise infrastructure there is not always the possibility to check certificates for revocation. The target server from a certificate is not always accessible, e.g. AWS Cloud on Premise. I need to be able to disable the certificate revocation check.
I customized the documentation in the configuration and added the CheckCertificateRevocation attribute. The SslStream is now extended by a variation in the AuthenticateAsClient method. 
The risk that a defect is caused by this change is low. Also there is no breaking change, because the default: CheckCertificateRevocation=true remains the same. 
Please record this changerequest. Thank you.
=> add CheckCertificateRevocation of SslStream.AuthenticateAsClient to Configuration

src/StackExchange.Redis/ConfigurationOptions.cs, src/StackExchange.Redis/SocketManager.cs
With async-heavy workloads the default Shared instances' 10 workers are not always enough. With a dedicated SockerManager the worker count is only 5 and not configurable.
This PR
- Adds overload to SocketManager exposing the workerCount so that is configurable.
- Updated ConfigurationOptions XML comment to align with how the SockerManager.Shared implementation works
Should solve https://github.com/StackExchange/StackExchange.Redis/issues/1035
=> Make SocketManager worker count configurable

docs/Basics.md, docs/PubSubOrder.md
First, the link from Basics doesn't work. Second, the docs code samples appear backward, in addition to the casing of the `Subscribe` method being off.
=> Improve pub/sub order documentation

src/StackExchange.Redis/PhysicalBridge.cs
Fixing a bug where READONLY is run before AUTH when reconnecting to clustered Slaves and since Readonly is run as Fire and Forget we never get an error either. 
This causes MOVED errors until the Multiplexer is recreated (easily seen when NoRedirect is specified) or all MOVED errors are handled internally but this means the Slaves are not at all used to distribute load which can cause connection issues with much smaller loads.
=> Fixing a bug where READONLY is run before AUTH. 

src/NRediSearch/Client.cs, src/NRediSearch/Suggestion.cs, tests/NRediSearch.Test/ClientTests/ClientTest.cs, tests/NRediSearch.Test/RediSearchTestBase.cs
- Updated module so we're testing the right thing
- More output in the logging path for diagnosing issues
- Remove all the FLUSHDB calls masking issues
- Handle duplicate documents in latest module
Note: **locally** (on WSL 2), this fixes some issues and introduces stability but *does not* fix 2 scoring issues. Suggestions are coming back with scores > 1.0, which by the documentation is not supposed to happen...so I'm not sure what should be happening here. Here's the local WSL fail:
```
NRediSearch.Test.ClientTests.ClientTest.TestGetSuggestionWithScore:
Message: 
StackExchange.Redis.RedisCommandException : Missing required fields:  score not within range: 2.11660146713257
Stack Trace: 
SuggestionBuilder.Build() line 99
Client.GetSuggestionsWithPayloadAndScores(RedisResult[] results) line …
```
=> NRediSearch Test Suite Fixes

src/StackExchange.Redis/ConfigurationOptions.cs
Hi,
i have make a pull request: @https://github.com/StackExchange/StackExchange.Redis/pull/1234
but it has a Bug. When the Config is Clone i have forgot the copy for the attribute CheckCertificateRevocation.
Now this request do that. Sorry for my fail.
=> fix forgotten clone config attribute CheckCertificateRevocation

tests/StackExchange.Redis.Tests/Config.cs
Clarifies how IPv6 needs to be expressed in example usage.
=> Add test for #1183

src/StackExchange.Redis/ExceptionFactory.cs, tests/StackExchange.Redis.Tests/ExceptionFactoryTests.cs, tests/StackExchange.Redis.Tests/Expiry.cs
In going through issues I see many users confused by `Unspecified/` and it really served no purpose. Let's get a quick win (and add a test for it).
Also, WSL2 it appears has clock jitter - we can accommodate that while having a valid test, fixing that local case.
=> Remove Unspecified/ from errors and test tweaks

src/StackExchange.Redis/RedisKey.cs, src/StackExchange.Redis/RedisValue.cs, tests/StackExchange.Redis.Tests/FSharpCompat.cs
Asked for in #831 and low overhead so why not! I didn't do `RedisChannel` since it already has a constructor available. Tests added to ensure these are used in a way we don't break them.
=> Add F# compatibility enhancements for #831

src/StackExchange.Redis/KeyspaceIsolation/WrapperBase.cs, tests/StackExchange.Redis.Tests/Scripting.cs
The implementation of ScriptEvaluateAsync in WrapperBase is incorrect and ignores the keyspace.
=> Fix keyspace isolation with ScriptEvaluateAsync

src/StackExchange.Redis/PhysicalBridge.cs
We recently encountered an issue where we repeatedly (for several hours) got the exception "No connection is available to service this operation". Using version 2.0.601 (with `AbortOnConnectFail` set to false)  running on asp.net core, in Azure and connecting to an Azure Redis instance. This was only resolved by a restart of the instance, other application instance could connect to the redis instance during this time
The full exception was as follows
```
No connection is available to service this operation: SMEMBERS XXXX; An existing connection was forcibly closed by the remote host; IOCP: (Busy=1,Free=999,Min=2,Max=1000), WORKER: (Busy=0,Free=32767,Min=2,Max=32767), Local-CPU: n/a
SocketFailure on xxx.redis.cache.windows.net:6380/Interactive, Idle/Faulted, last: GET, origin: …
```
=> PhysicalBridge always returns NoConnection after exception during message write / connection flush

docs/ReleaseNotes.md, src/StackExchange.Redis/EndPointCollection.cs, tests/StackExchange.Redis.Tests/Config.cs
re-implement GetEnumerator in EndPointCollection to be a bit more forgiving to concurrent changes during iteration
=> fix error with DNS resolution breaking endpoint iterator

src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/Interfaces/IServer.cs, tests/StackExchange.Redis.Tests/BasicOps.cs, tests/StackExchange.Redis.Tests/ConnectFailTimeout.cs, tests/StackExchange.Redis.Tests/ConnectToUnexistingHost.cs, tests/StackExchange.Redis.Tests/ConnectingFailDetection.cs, tests/StackExchange.Redis.Tests/ExceptionFactoryTests.cs, tests/StackExchange.Redis.Tests/Failover.cs, tests/StackExchange.Redis.Tests/Issues/Issue1101.cs, tests/StackExchange.Redis.Tests/Issues/SO24807536.cs, tests/StackExchange.Redis.Tests/Migrate.cs, tests/StackExchange.Redis.Tests/PubSub.cs, tests/StackExchange.Redis.Tests/Sentinel.cs, tests/StackExchange.Redis.Tests/TestBase.cs
This changes does the following:
- Moves the broadcast to be only before the master reconfiguration to both before *and* after - a fix following https://github.com/StackExchange/StackExchange.Redis/commit/88dcf0c989b25623fb8ffb1f4d48c24593246cfe to fix the gap.
- Tweaks tests by overall lessening runtime (and thus build server time). Overall, fixes a few static timeouts to be conditional (so they short circuit faster if met), and brings some tests that were some variant of the above into RELEASE since they're safe now.
- Changes `UntilCondition` to take a `TimeSpan`, just because clearer. Even though I IntelliSense completed `.FromMinutes()` earlier and watched it like an idiot for a while...I stand by this decision!
- Locks the `ITestOutputHelper` writer because...that was jacked up in …
=> Fix up boadcasts, tests, and logging across the board

src/StackExchange.Redis/ExceptionFactory.cs
Just trying to clarify this message and figured we can rev on a PR quickly.
Old message:
> To create a disconnected multiplexer, disable AbortOnConnectFail.
New message proposal:
> Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.
=> Message clarification for #1287

src/StackExchange.Redis/ConnectionMultiplexer.cs, tests/StackExchange.Redis.Tests/Sentinel.cs
We were throwing in event handlers...that's not good. Also post-thread sleep in timer callbacks.
=> Sentinel: remove Thread.Sleep and throws

src/StackExchange.Redis/ConfigurationOptions.cs, tests/StackExchange.Redis.Tests/SSL.cs
Currently, SslProtocols is not being included in ConfigurationOptions.ToString(). The PR address the issue.  #1407
=> Including SslProtocols in ConfigurationOptions.ToString()

src/StackExchange.Redis/ConfigurationOptions.cs, src/StackExchange.Redis/ServerEndPoint.cs
- adds new config options for cn+pw authentication against redis 6
- currently no inbuilt test, because we need to figure out a redis 6 testing setup
- no support for extended `ACL` command set yet
1. because they aren't entirely nailed down yet, and
2. because they aren't critical path to being able to use it, because
3. everything still works fine via all-encompassing `Execute` fallback
=> allow auth with user (redis 6)

src/StackExchange.Redis/CommandMap.cs
Sentinel servers can be set to require auth like regular servers.
=> Add auth to commandmap for sentinel servers

src/StackExchange.Redis/RedisResult.cs, tests/StackExchange.Redis.Tests/RedisResultTests.cs
Previously it would only parse the first half of the array.  Also added test coverage for this method.
=> Fix RedisResult.ToDictionary.  

docs/ReleaseNotes.md, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/Interfaces/IServer.cs, src/StackExchange.Redis/RedisServer.cs, tests/StackExchange.Redis.Tests/Databases.cs, tests/StackExchange.Redis.Tests/TestBase.cs
- impacts `DBSIZE`, `FLUSHDB`, `KEYS`, `SCAN`
- changes default parameter value from 0 to -1 (needs rebuild of caller to recognize, this is fine)
- adds a helper method to standardize the behavior between call-sites
=> Apply default database rules on `IServer`

src/StackExchange.Redis/ResultProcessor.cs, src/StackExchange.Redis/StreamGroupInfo.cs
"last-delivered-id" was added to XINFO GROUPS in the 5.0 timeframe.
It can be useful as a proxy for stream lag when compared to StreamInfo,LastGeneratedId
However, the redis-doc wasn't updated (see https://github.com/antirez/redis-doc/pull/1318)
This PR simply adds the field to the StreamGroupInfo response.
=> add last-delivered-id to StreamGroupInfo

docs/Timeouts.md
The previous link redirected the user to the .NET 1.1 docs (`vs.71`) for `<processModel>`. This page did not contain any references to `minIoThreads`. I've corrected this by changing the link to point to .NET 4.0 (`vs.100`) which contains the relevant documentation.
No code was harmed in the making of this PR - only the [`Timeouts`](https://stackexchange.github.io/StackExchange.Redis/Timeouts) documents page was changed. :)
=> Change processModel docs link on Timeouts page

appveyor.yml, tests/NRediSearch.Test/ClientTests/ClientTest.cs, tests/NRediSearch.Test/RediSearchTestBase.cs, tests/RedisConfigs/docker-compose.yml, tests/StackExchange.Redis.Tests/Helpers/TestConfig.cs
This moves NRedisSearch to docker-compose, and also moves AppVeyor Unbuntu builds to use docker-compose. Unfortunately we can't do this on Windows due to how the build VMs are setup. If we're comfortable doing Docker-only (we didn't want to jump in there), we could cleanup the `.sh` files afterwards.
Additionally, this removes the `redisearch.so` module from our repo and the code to install it (only in tests). Since this broke with every server mismatch, using their official Docker image that'll always work is much saner and simpler.
Fixes NRedisSearch test failures in #1488, but also `master` branch.
=> Builds & Local: Move NRedisSearch to :6385 and Docker

docs/ReleaseNotes.md, src/StackExchange.Redis/ResultProcessor.cs
- uses `GetItems()` which provides access to the raw tokenized stream data, without any allocations, instead of `GetItemsAsValues()` which creates a `RedisValue[]` of copies
- generalizes the existing `StreamInfoKeys` (which is what used this first) to `KeyValuePairParser`
=> avoid the array (multi-bulk) allocation in sentinel processors

src/StackExchange.Redis/CursorEnumerable.cs, src/StackExchange.Redis/RedisBase.cs, src/StackExchange.Redis/RedisDatabase.cs, src/StackExchange.Redis/RedisServer.cs
1. *SCAN now logs pageSize and pageIndex in the exception data
2. switch all *SCAN cursors from long to RedisValue, because redis-cluster-proxy
=> Improve *SCAN logging and fix redis-cluster-proxy cursor problem

src/StackExchange.Redis/ResultProcessor.cs
The assumption in the result processor was that it must have results to be valid, but that's not correct. If a sentinel has 0 replicas (only 1 master), that's a perfectly valid state. This adjusts the result processor logic to be more correct.
=> Fix for #1512

src/StackExchange.Redis/ConfigurationOptions.cs, src/StackExchange.Redis/ConnectionMultiplexer.cs, tests/StackExchange.Redis.Tests/Config.cs, tests/StackExchange.Redis.Tests/Sentinel.cs
This makes it so that when using a configuration string to connect that we only parse the configuration string and not set any defaults on it until it is forwarded on to the connect methods that take `ConfigurationOptions`
=> Fix sentinel default port when connecting with configuration string

src/StackExchange.Redis/ResultProcessor.cs
Fixes #1567.
Looking for suggestions on how to add test coverage for this change. It seems like `StackExchange.Redis.Tests.Streams.StreamGroupConsumerInfoGet()` would be appropriate, but I'm not sure how to artificially increase the idle time of the consumer.
=> Implement KeyValuePairParser.TryRead for Int64

src/StackExchange.Redis/RedisDatabase.cs, tests/StackExchange.Redis.Tests/Lex.cs
If the `stop` value is `default(RedisValue)` and is compared against a `start` value that isn't the result from `start.CompareTo(stop)` is `1`, which would reverse the range, which would cause the library to emit an incorrect query to Redis. 
I figured this change would have far fewer impacts than changing how `RedisValue.CompareTo` works. 
This should close issue #992
=> Do not invert the range if the `max` value is `default(RedisValue)`

src/StackExchange.Redis/CommandMap.cs, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/Enums/RedisCommand.cs, src/StackExchange.Redis/Interfaces/IServer.cs, src/StackExchange.Redis/Message.cs, src/StackExchange.Redis/RawResult.cs, src/StackExchange.Redis/RedisLiterals.cs, src/StackExchange.Redis/RedisServer.cs, src/StackExchange.Redis/ResultProcessor.cs, src/StackExchange.Redis/Role.cs, src/StackExchange.Redis/ServerRole.cs, tests/StackExchange.Redis.Tests/Roles.cs, tests/StackExchange.Redis.Tests/Sentinel.cs
This PR implements the ROLE command (#1451): https://redis.io/commands/role#sentinel-output . Redis implementation: https://github.com/redis/redis/blob/unstable/src/replication.c#L2672
Because the result format is pretty different for each instance type, we return a base Role type that the caller has to type check to get to the values specific to the instance type.
I've tested the master and replica cases locally. I haven't tested sentinel, but that one is the most straightforward.
=> Implement ROLE command

src/StackExchange.Redis/ConfigurationOptions.cs
I believe the change [from this old 2018 PR](https://github.com/StackExchange/StackExchange.Redis/commit/e4d3a782d27e8f02a4dec261f69acda5b1aa8066) is incorrect -- at least with today's behavior.
To determine this revert is required I setup two Redis instances and ran "SET environment first" on one and "SET environment second" on the other. I used the computer's hostfile to control which IP my DnsEndpoint resolved to. I briefly disconnected my network to trigger reconnection code. 
```
while (true) {
try {
var environment = await connection.GetDatabase().StringGetAsync("environment");
programLogger.LogInformation(environment);
} catch (Exception) {
// squelch
} finally {
await Task.Delay(TimeSpan.FromSeconds(5));
}
}
```
Here are the behaviors I see if I use a DnsEndpoint and the IPs for …
=> Revert misleading change to documentation

.github/workflows/Linux.yml, Directory.Build.props
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Actions: Upgrade NerdBank to fix some errors

src/NRediSearch/NRediSearch.csproj, src/NRediSearch/Query.cs, src/NRediSearch/Schema.cs, src/StackExchange.Redis/ClusterConfiguration.cs, src/StackExchange.Redis/ConfigurationOptions.cs, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/Format.cs, src/StackExchange.Redis/RedisDatabase.cs, src/StackExchange.Redis/RedisFeatures.cs, src/StackExchange.Redis/StackExchange.Redis.csproj, tests/NRediSearch.Test/NRediSearch.Test.csproj, tests/StackExchange.Redis.Tests/FormatTests.cs, tests/StackExchange.Redis.Tests/GarbageCollectionTests.cs, tests/StackExchange.Redis.Tests/GeoTests.cs, tests/StackExchange.Redis.Tests/Lists.cs, tests/StackExchange.Redis.Tests/StackExchange.Redis.Tests.csproj, toys/TestConsole/TestConsole.csproj
- add netcoreapp3.1 TFM
- aim here is to enable unix sockets, but it also means we can simplify dep tree
- drop net461/netcoreapp2.1 from tests
- fix broken assembly reference for compression and runtime interop (see #1592)
=> Build changes - netcoreapp3.1 and dependencies

.github/workflows/Linux.yml, Directory.Build.targets, tests/NRediSearch.Test/NRediSearch.Test.csproj, tests/StackExchange.Redis.Tests/StackExchange.Redis.Tests.csproj
Getting some Actions error logging up in here, logs where the test failures are in the diff (if the change is present), color codes the console, and splits the tests into steps for the 2 projects so that it's easier to see what went wrong. See the action run on this PR to see. Good to merge for helping us get `main` back green.
=> GitHub Actions logging

src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/PhysicalBridge.cs, src/StackExchange.Redis/ServerEndPoint.cs
Multiple people had previously complained that whenever there is a cluster failover, they experience Connection Exceptions for at least close to a minute. 
During investigation, @joroda  found that this is due to the fact that config check is done roughly every 60 seconds by default and during failover it has to be done almost immediately to eliminate the errors. 
This fix shows significant improvement from the tests we did. it reduces errors to around 2 seconds for the 90th percentile case compared to around 56 seconds of errors for 90th percentile right now.
=> ForceReplication during failovers to reduce errors in clustered scenarios

.github/workflows/Linux.yml, tests/NRediSearch.Test/ClientTests/ClientTest.cs, tests/NRediSearch.Test/RediSearchTestBase.cs, tests/RedisConfigs/docker-compose.yml
Fundamentally, JRediSearch is doing this, and bases test assumptions on it. To get back to a decent/matching state, we need to do the same. It also brings in the hash failure check from https://github.com/RediSearch/JRediSearch/blob/f1d7e2ed64a18e99b31b3b7fe48bb972c00e3999/src/test/java/io/redisearch/client/ClientTest.java#L403-L408
=> NRediSearch build fixes

appveyor.yml
This is covered by Actions now, and AppVeyor is currently flipping out due to something on their end...let's kill it.
=> Builds: AppVeyor: remove Ubuntu

src/StackExchange.Redis/PhysicalConnection.cs
Fixes #1438 
When flushing during FlushSync we are specifying a timeout to the Task, but when this timeout gets hit the underlying task is still running. The thread that invoked FlushSync continues and releases the MutexSlim that is protecting the io pipe allowing another thread to obtain the MutexSlim and try to run operations on the pipe. 
To fix use the cancellation token that can be passed to PipeWriter.FlushAsync. 
An alternative to this is to not specify a timeout. There are 2 additional locations that flush the pipe neither of those locations specify a timeout they just simply await the Task.    Generally the timeouts are driven by how long an operation waits to obtain the MutexSlim
=> fix for mutex slim being released too early during flush operation

docs/Configuration.md, src/StackExchange.Redis/ConfigurationOptions.cs, tests/StackExchange.Redis.Tests/Config.cs
This configuration setting can't be set right now using connection string. 
Usage example: 
"redishost:6380,ssl=True,checkCertificateRevocation=false"
=> Allow CheckCertificateRevocation to be set on connection string

.github/workflows/CI.yml
This fixes the .NET 5 SDK issue on GitHub Actions builds (the few errors here are transient server issues).
We can revert this once it lands on the Actions images.
=> GitHub Actions: add .NET 5.x install

docs/ReleaseNotes.md, src/StackExchange.Redis/PhysicalBridge.cs
See also #1574; rather than buffering (which helps, but just kicks the problem down a little), this moves `ProcessBacklog` to be truly async; it also checks for work *before* attempting to acquire the lock, to short-circuit high contention scenarios
=> Async backlog

src/StackExchange.Redis/EndPointCollection.cs, src/StackExchange.Redis/Format.cs, src/StackExchange.Redis/StackExchange.Redis.csproj, tests/StackExchange.Redis.Tests/Config.cs, tests/StackExchange.Redis.Tests/StackExchange.Redis.Tests.csproj
- marked by a leading `!` in the configuration string, i.e. `!/foo` connects to `/foo` over a unix domain socket
- only available on .builds for NET Core 3.1 and above; in theory we could also support .NET Standard 2.1, but I kinda don't want to add that as a TFM
(the actual work to *connect* via unix domain sockets has worked for a long time - `Socket` deals with it)
=> add support for parsing and formatting unix domain sockets

src/StackExchange.Redis/Interfaces/IDatabase.cs
Typo in the XML Documentation in IDatabase.cs
'_defaults_' was spelled as '_detaults_'
=> Fixing Typo in IDatabase.cs in XML Documentation

src/StackExchange.Redis/Interfaces/IDatabase.cs, src/StackExchange.Redis/Interfaces/IDatabaseAsync.cs
I experienced an unexpected behaviour when using HashIncrementAsync on a hashset field that was a string.
I was using FireAndForget which initially hid my error... however I was relying on the wording of the intellisense which stated;
```
If field does not exist **or holds a string that cannot be interpreted as integer**, the value is set to 0 before the operation is performed.
```
So I (wrongly) assumed my below test would work and "abc" would be reset to "0" and then incremented by 1.
```csharp
[Fact]
public async Task dtHashSet()
{
await _redisCacheSvc.db.HashSetAsync("prefix:key", new HashEntry[] { new HashEntry("hashField", "abc") });
var before = await _redisCacheSvc.db.HashGetAsync("prefix:key", "hashField");
Assert.Equal("abc", before);
var after = await …
```
=> corrects wording of HashIncrement/HashDecrement summaries

src/StackExchange.Redis/LuaScript.cs, src/StackExchange.Redis/ScriptParameterMapper.cs, tests/StackExchange.Redis.Tests/Scripting.cs
While `ReadOnlyMemory<byte>` is convertible to `RedisValue`, the type is not allowed as a Lua script parameter.
I can see the restriction doesn't seem to be necessary and the type could work as expected on Lua scripts.
How to reproduce:
```
1. const string Script = "return @ident";
2. var prepared = LuaScript.Prepare(Script);
3. var db = conn.GetDatabase();
4. 
5. var val = prepared.Evaluate(db, new { ident = new ReadOnlyMemory<byte>(new byte[] { 4, 5, 6 }) });
6. Assert.True(new byte[] { 4, 5, 6 }.SequenceEqual((byte[])val));
```
Here line 5 will fail with
```
System.ArgumentException : ps
Parameter name: Expected [ident] on [<>f__AnonymousType3`1[[System.ReadOnlyMemory`1[[System.Byte, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Memory, …
```
=> Allow ReadOnlyMemory<byte> as Lua Script parameter type

src/StackExchange.Redis/RedisValueWithExpiry.cs
Allows RedisValueWithExpiry to be used in unit tests when an IDatabase is mocked.
Resolves #1730
=> Update RedisValueWithExpiry constructor to be public

src/StackExchange.Redis/Message.cs, src/StackExchange.Redis/Profiling/ProfiledCommand.cs
Decreasing diff on #1714 to make things a bit easier to read.
=> Profiler naming fixes

src/StackExchange.Redis/ResultProcessor.cs
Inspired on ValueStopWatch: https://github.com/dotnet/extensions/blob/master/src/Shared/src/ValueStopwatch/ValueStopwatch.cs, I'm removing the instance of Stopwatch from TimerMessage.
There's a change of behavior here:
We're not starting latency measurement when message is instantiated, but right before it is written to network.
=> Start measuring Ping latency closer to sending request and remove Stopwatch instance

src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/PhysicalBridge.cs, src/StackExchange.Redis/ServerEndPoint.cs
Fixes info command storm on a disconnect
After a master node disconnect performs ConfigCheckSeconds on replica nodes with an exponential backoff
=> Improving ConfigCheckSeconds for a faster failover detection

src/StackExchange.Redis/ExceptionFactory.cs
Adjust logic to display suggestion for setting AbortOnConnectFail=false only when it's currently true.
Mentioned in these issues:
#1744
#1287
=> Invert check for AbortOnConnectFail advisory message

tests/StackExchange.Redis.Tests/ConnectFailTimeout.cs, tests/StackExchange.Redis.Tests/ConnectToUnexistingHost.cs, tests/StackExchange.Redis.Tests/ConnectionFailedErrors.cs, tests/StackExchange.Redis.Tests/TestBase.cs
Also for #1748. Using TaskCreationOptions.LongRunning can give us a temporary boost in thread numbers for those tests which want to block the thread in failed connection scenarios (these tend to block the thread for a while, which can lead to connectivity issues from exhausting the worker thread pool for other tests).
=> For test reliability - use TaskCreationOptions LongRunning hint for 'failed connection' tests

tests/NRediSearch.Test/ClientTests/AggregationBuilderTests.cs, tests/StackExchange.Redis.Tests/Failover.cs, tests/StackExchange.Redis.Tests/GarbageCollectionTests.cs, tests/StackExchange.Redis.Tests/Sentinel.cs
This is a partial fix for Issue #1748. While debugging the issue further, I found that one cause of test worker threads being blocked for a long time was bad old `Thread.Sleep()`.
This fix eliminates all the `Thread.Sleep()`s from test code.
(With this fix there is only one remaining sleep call now in the product code, in GetSentinelMasterConnection(), which is a public synchronous API. It would probably be a good idea to deprecate that API and encourage people to use an Async API instead.)
=> For Issue1748: Thread.Sleep fixes

docs/Timeouts.md, tests/StackExchange.Redis.Tests/BatchWrapperTests.cs, tests/StackExchange.Redis.Tests/DatabaseWrapperTests.cs, tests/StackExchange.Redis.Tests/TransactionWrapperTests.cs, tests/StackExchange.Redis.Tests/WrapperBaseTests.cs
This PR is also a *partial* fix for #1748.
I found that another common cause of too many blocked worker threads while running tests is the code for dynamic generation of mock object Types. This code hits contention due to exclusive locking i.e. the test threads block waiting for each other, all to take turns being the one to then use a hefty amount of CPU to generate some types dynamically. (And once one thread gets unblocks, it then goes busy generating another type, and continues to block all the other Moq threads...)
The proposed solution is to ensure we only run one Moq-dependent test at a time, so that the Moq-dependent tests don't actually have to wait to acquire the lock.
=> For test reliability and 1748:- don't parallelize Moq tests.

tests/StackExchange.Redis.Tests/Failover.cs
This is not a deeply-analyzed change, but based on one test run on my machine, I suspect these timeouts are probably just a little too short to be reliable while running tests in parallel.
=> Increase timeouts for ConfigVerifyReceiveConfigChangeBroadcast test

src/StackExchange.Redis/ConnectionMultiplexer.cs
When this was refactored long ago, we went from a counter starting at 1 (which handled the first run) to a string reason (which defaults to empty). Combined with the `||` clause format, this subtly introduced a re-entrancy bug where a subsequent run can enter during the first run (where first was true, so no exchange for reason occurred).
This was causing several Sentinel issues due to on connect handlers setting config as nodes returned and ultimately the `Set<T>` triggering a `ReconfigureIfNeeded`....and actually running, while the original config was still in progress. This led to all sorts of race oddness especially if one endpoint was any kind of significantly different in timing than another.
Note: the other changes are only labels on the bool arguments for clarity at the call …
=> ReconfigureAsync: fix re-entrancy issue

src/StackExchange.Redis/ConnectionMultiplexer.cs
In short, we could get in a state where `IsReplica` could be true, but we couldn't use it because it was unselectable via this path, especially on a reconnect race. This caused failures in other Sentinel testing, specifically the `NoConnectionAvailable` variety on `DemandMaster` sanity check gets, because we had a replica, it was connected, but the flags said we couldn't use it. That should _never_ be the case and this additional check at the flag set site ensures it.
In testing, it looked like this (local changes here are logging this condition):
=> Unselectable flag race fix

src/StackExchange.Redis/ServerEndPoint.cs, tests/StackExchange.Redis.Tests/Sentinel.cs, tests/StackExchange.Redis.Tests/SentinelBase.cs, tests/StackExchange.Redis.Tests/SentinelFailover.cs
This allows more control and isolation of the failover portion (as with other tests). Also adds a bit more logging as to endpoint state to help debug issues.
=> Sentinel: split tests

.github/workflows/CI.yml, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/PhysicalBridge.cs, src/StackExchange.Redis/ServerEndPoint.cs, tests/StackExchange.Redis.Tests/Cluster.cs, tests/StackExchange.Redis.Tests/Helpers/TextWriterOutputHelper.cs, tests/StackExchange.Redis.Tests/Migrate.cs, tests/StackExchange.Redis.Tests/MultiMaster.cs
In GitHub CI if a person doesn't have permissions (to this repo) then the CI fails from trying to *report* test results. It's fine if tests fail and blow us up as intended, but inability to report them shouldn't. We don't see pretty test results when this happens, but every fork won't be red for no reason either.
In removing the fire and forget flags from the primary tracer path to await it, I've realized that write path _won't actually complete_ until the buffer fires, creating a deadlock (we should re-evaluate that path, give we write _but don't observe the result_). The tracers purpose here is to ensure the connection is still working, as a sort of keep-alive, mechanisms elsewhere will handle failure and reconnect if so determined (e.g. via `ReconfigureIfNeeded` paths). In short: we …
=> Fixes for #1762 & Don't fail on *reporting*

src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/ResultProcessor.cs, src/StackExchange.Redis/ServerEndPoint.cs, tests/StackExchange.Redis.Tests/Migrate.cs, tests/StackExchange.Redis.Tests/Sentinel.cs
`await SendTracer(log);` in `OnConnectedAsync` is still hanging sometimes (the log line after it doesn't fire), and the task from that overall local fun is in `WaitingForActivation` status. This happens in the already-connected case and I'm not sure why. This causes the `MultiMaster` sporadic test failure when it occurs.
I'm not spotting the race just yet, but close to a full solution here if we can nail it down.
/cc @TimLovellSmith @mgravell for eyes please - run MultiMaster tests *with the whole suite* to get a failure locally, but I'd say the chances are maybe 1 in 10 of a repro here...better in CI.
=> More connection/logging tweaks

src/StackExchange.Redis/ResultProcessor.cs, tests/StackExchange.Redis.Tests/SentinelBase.cs, tests/StackExchange.Redis.Tests/SentinelFailover.cs
This should help the flakiness in this test, it's a race described in #1783, but in the test not the functionality.
=> Sentinel: fix for #1783

src/StackExchange.Redis/ConnectionMultiplexer.cs
Hi. I faced a problem with 'ConnectionMultiplexer': when it loses connection with Redis cluster, 'OnManagedConnectionFailed' event handler creates timer, which tries to 'SwitchMaster'. Timer ticks every second, but there is PLINQ query in 'GetConfiguredMasterForService' method, that leads to constantly threads starting (threads start faster than they exit). And if disconnect time is long enough, I get thread/memory leak in service.
PR contains hotfix of a problem with timer (timer starts next iteration only after previous iteration complete). But maybe you should take a closer look at PLINQ queries (they seem superfluous).
Also, I commented `TextWriter.Null` creation in 'SwitchMaster', because it seems like useless memory allocations (you handle nullable LogProxy).
=> OnManagedConnectionFailed thread/memory leak fix

tests/StackExchange.Redis.Tests/SentinelFailover.cs, tests/StackExchange.Redis.Tests/SharedConnectionFixture.cs, tests/StackExchange.Redis.Tests/TestBase.cs
The Sentinel issue appears to be server-side, it's waiting 10 seconds to issue the REPLICAOF after a failover. This seems to be a Redis issue I haven't narrowed down yet, but increasing logging here to help tests in general.
=> Tests: better logging

src/StackExchange.Redis/ChannelMessageQueue.cs, src/StackExchange.Redis/RedisFeatures.cs
Best practice cleanup, since we're overriding `.Equals()`
=> Add == & != operators for ChannelMessaege and RedisFeatures

docs/ReleaseNotes.md, src/StackExchange.Redis/ServerEndPoint.cs
A few stack-traces have shown `GetOutstandingCount` participating in faults due to broken sockets etc; however, we use `GetOutstandingCount` from *within* those handlers, so: allowing it to blow up could be masking the original/underlying exception; fix that, by making `GetOutstandingCount` best-efforts only
=> prevent GetOutstandingCount from throwing

src/StackExchange.Redis/PhysicalBridge.cs
=> Fixes "messages get sent out-of-order when a backlog is created by another thread"

docs/ReleaseNotes.md, src/StackExchange.Redis/ConnectionMultiplexer.cs, tests/StackExchange.Redis.Tests/Cluster.cs, tests/StackExchange.Redis.Tests/Helpers/TextWriterOutputHelper.cs, tests/StackExchange.Redis.Tests/MultiMaster.cs, tests/StackExchange.Redis.Tests/TestBase.cs
Prefix each entry with a timestamp that looks like:
```
18:18:47.9261: Connecting (async) on .NET Core 3.1.16
18:18:47.9263: cachename.redis.cache.windows.net:6380/Interactive: Connecting...
18:18:47.9463: cachename.redis.cache.windows.net:6380: BeginConnectAsync
18:18:47.9483: 1 unique nodes specified
```
=> Add .NET version and timestamp on default logger rows

docs/ReleaseNotes.md, src/StackExchange.Redis/Condition.cs, tests/StackExchange.Redis.Tests/Transactions.cs
Adding some new condition overloads for XLEN, useful for deleting empty streams in a safe method. It's a very simple change, one line to the length condition implementation plus the overloads.
Tests have been added and pass, though I don't have the infrastructure to run the failover/cluster/etc tests. I can include the .trx file if that's important.
I would have liked to add more conditions, like one that calls XPENDING to examine the number of pending messages, but that would need a new condition implementation with different messages and more complicated code to examine the results. Maybe I'll do it in another pull request, if I find the time.
=> Stream Length Transaction Conditions

src/StackExchange.Redis/PhysicalConnection.cs
This prevents a disposal race from killing us in connection phases and such, protected against in the counters above in Unofficial (see https://github.com/mgravell/Pipelines.Sockets.Unofficial/blob/19b141f30fe2485dd79993be0ac87a9fc6b34b74/src/Pipelines.Sockets.Unofficial/SocketConnection.cs#L235) but not here - adding the same protection guard.
Stack trace of such an error:
```
----- Inner Stack Trace -----
at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
at Interop.Winsock.ioctlsocket(SafeSocketHandle socketHandle, Int32 cmd, Int32& argp)
at System.Net.Sockets.SocketPal.GetAvailable(SafeSocketHandle handle, Int32& available)
at System.Net.Sockets.Socket.get_Available() …
```
=> Socket available bytes check: add a disposal guard

src/StackExchange.Redis/PhysicalBridge.cs
Part of #1847, giving better debug information when this happens.
=> Add a backlog status that tracks non-activated backlogs

docs/ReleaseNotes.md, src/StackExchange.Redis/PhysicalBridge.cs
Pain point in the last release was a spiral of death triggered (or at least: exacerbated) by the backlog processor
=> Use a dedicated thread, rather than the thread-pool, for the backlog processor

docs/ReleaseNotes.md, src/NRediSearch/Schema.cs, tests/NRediSearch.Test/ClientTests/ClientTest.cs
Adding the ability to add sorted tag fields in indices per #1838
Note: When serializing the arguments RediSearch cares about the order of the separator and sortable arguments, hence after calling `base.SerializeRedisArgs`, if the index is sortable and removes the sortable flag, and then adds it back after the separator flag is added.
=> Adding sortable tag field support & UNF support

docs/ReleaseNotes.md, src/StackExchange.Redis/Interfaces/IDatabase.cs, src/StackExchange.Redis/Interfaces/IDatabaseAsync.cs, src/StackExchange.Redis/KeyspaceIsolation/DatabaseWrapper.cs, src/StackExchange.Redis/KeyspaceIsolation/WrapperBase.cs, src/StackExchange.Redis/RedisDatabase.cs, tests/StackExchange.Redis.Tests/DatabaseWrapperTests.cs, tests/StackExchange.Redis.Tests/WrapperBaseTests.cs
Add support for count argument to ListLeftPop, ListLeftPopAsync, ListRightPop, and ListRightPopAsync
Optional Count argument was added in Redis 6.2
=> Add support for count argument to ListLeftPop, ListLeftPopAsync, ListRightPop, and ListRightPopAsync

docs/ReleaseNotes.md, src/StackExchange.Redis/StreamEntry.cs
Makes `StreamEntry` constructor public to fixes #1922
=> Makes StreamEntry constructor public

docs/ReleaseNotes.md, src/StackExchange.Redis/BufferReader.cs
total consumed was `int`, which was causing integer overflow issues with 2GiB+ payloads, manifesting in an `ArgumentOutOfRangeException` in `SnapshotPosition()`
=> fix #1926 integer overflow in BufferReader (make total consumed 64-bit)

docs/ReleaseNotes.md, src/StackExchange.Redis/ConfigurationOptions.cs, tests/StackExchange.Redis.Tests/Config.cs
This more reflects reality today and if we cannot detect a server version (e.g. config has INFO disabled as in #1926) then we'll do smarter things like use SCAN over KEYS.
=> Default versions: assume v2.8 as a minimum (SCAN over KEYS) and 4.0+ in Azure

src/StackExchange.Redis/RedisDatabase.cs, tests/StackExchange.Redis.Tests/Profiling.cs
Currently the constructor for ScriptEvalMessage that takes a SHA1 hash, and sends the `EVALSHA` command, initializes the base Message class's command to `RedisCommand.EVAL` instead of `RedisCommand.EVALSHA`.
=> Initialize ScriptEvalMessage with the correct command

tests/StackExchange.Redis.Tests/SanityChecks.cs
Adding a sanity check to ensure this doesn't regress as long as we support .NET Full Framework.
Thanks @ltrzesniewski!
=> Tests: ensure we're not referencing ValueTuple

tests/StackExchange.Redis.Tests/Expiry.cs, tests/StackExchange.Redis.Tests/Issues/SO25113323.cs
I hit an oddity in the Docker setup locally today where the clock drifted ~10 seconds and these tests were failing because they make an inherent assumption of local clock == server clock. This aims to remove that assumption from the test suite and treat server time as accurate or account for the skew when checking TTLs.
=> Tests: handle clock skew vs. test containers

docs/Streams.md
There is inconsistency between the usage of `events_stream` and `event_stream` in the documentation for Getting Started with Streams. If a user copies the sample code from the first part of the page to add to the stream and then the consumer group related code from the latter part of the page to consume, they may not notice the difference in the name of the stream and wonder why they are not receiving messages.
=> Update streams readme for consistency

.github/workflows/CI.yml, appveyor.yml, src/StackExchange.Redis/CommandTrace.cs, src/StackExchange.Redis/ConnectionMultiplexer.ReaderWriter.cs, src/StackExchange.Redis/StackExchange.Redis.csproj, tests/StackExchange.Redis.Tests/Config.cs, tests/StackExchange.Redis.Tests/Migrate.cs, tests/StackExchange.Redis.Tests/PubSub.cs, tests/StackExchange.Redis.Tests/StackExchange.Redis.Tests.csproj, tests/StackExchange.Redis.Tests/TestBase.cs, version.json
This adds a `net6.0` build (and test run) that uses the default thread pool for pipe scheduling rather than our scheduler. Namely due to 2 major changes since this was introduced:
1. Thread theft has long since been resolved (never an issue in .NET Core+)
2. Sync-over-async is an app problem, but should be much better in .NET 6.0+ which has changes specifically for this in thread pool growth (see https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/#threading)
Due to this combo of changes, we want to see if this behaves much better in the next alpha. The advantages are we move from 10 threads by default shared between connections to no dedicated threads for the scheduler. It has the following benefits:
1. While these threads were mostly idle (waiting for data), people …
=> v2.5 work: .NET 6.0: add build defaulting to the thread pool

src/StackExchange.Redis/PhysicalConnection.cs, tests/StackExchange.Redis.Tests/Expiry.cs
I got time backwards and the simulation was raising events in a race for a connection it _wasn't_, e.g. both interactive directions would still raise an event on the subscriber because I'm a dummy.
=> Tests: failure simulation and time fixes

src/StackExchange.Redis/PhysicalBridge.cs
In #1854 we switched to a `Thread` here to prevent the pile-up case, however under concurrent load this incurs a 10-11% penalty given backlogs aren't all that uncommon (due to the lock contention case). In .NET 6.0+, let's use the thread pool growth semantics to handle the stall case and use the cheaper `Task.Run()` approach.
Running the benchmarks from #1164 I was experimenting with on lock perf, I noticed a large perf sink in thread creation as a result of lock contention. For that benchmark as an example (high concurrent load) we're talking about a ~93 second -> ~84 second run reduction and similar wins in concurrent load tests.
=> Backlog: use a Task over Thread in .NET 6.0

src/StackExchange.Redis/PhysicalBridge.cs
Since Semaphore slim has been fixed on all the platforms we're building for these days, this tests moving back. Getting some test run comparison data, but all synthetic benchmarks are looking good. See https://github.com/mgravell/Pipelines.Sockets.Unofficial/issues/64 for details
Here's the main contention test metrics from those benchmarks:
|                        Method |    Runtime |         Mean |      Error |     StdDev | Allocated |
|------------------------------ |----------- |-------------:|-----------:|-----------:|----------:|
|            SemaphoreSlim_Sync |   .NET 6.0 |    18.246 ns |  0.2540 ns |  0.2375 ns |         - |
|                MutexSlim_Sync |   .NET 6.0 |    22.292 ns |  0.1948 ns |  0.1627 ns |         - |
|            SemaphoreSlim_Sync | .NET 4.7.2 | …
=> Writer: switch back to SemaphoreSlim

appveyor.yml
Eliminate the double builds on branches before a PR is open
=> AppVeyor: only build main branch

src/StackExchange.Redis/ExceptionFactory.cs, src/StackExchange.Redis/Message.cs, src/StackExchange.Redis/PhysicalBridge.cs, src/StackExchange.Redis/PhysicalConnection.cs
In DEBUG we had lots of additional logging around locks and flushes, but the reality is these are in a slower unoptimized state and heavily influencing the results especially of lock contention themselves. This removes a lot of the debug code we had when first building this around timings.
=> Debug: lots of pruning

src/StackExchange.Redis/ConfigurationOptions.cs, src/StackExchange.Redis/ConnectionMultiplexer.Threading.cs, src/StackExchange.Redis/ConnectionMultiplexer.Verbose.cs, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/Enums/CommandFlags.cs, src/StackExchange.Redis/ExceptionFactory.cs, src/StackExchange.Redis/Interfaces/ISubscriber.cs, src/StackExchange.Redis/Message.cs, src/StackExchange.Redis/PhysicalBridge.cs, src/StackExchange.Redis/RedisBatch.cs, src/StackExchange.Redis/RedisSubscriber.cs, src/StackExchange.Redis/ServerEndPoint.cs, src/StackExchange.Redis/ServerSelectionStrategy.cs, tests/StackExchange.Redis.Tests/AsyncTests.cs, tests/StackExchange.Redis.Tests/Config.cs, tests/StackExchange.Redis.Tests/ConnectFailTimeout.cs, tests/StackExchange.Redis.Tests/ConnectingFailDetection.cs, tests/StackExchange.Redis.Tests/ConnectionShutdown.cs, tests/StackExchange.Redis.Tests/PubSub.cs, tests/StackExchange.Redis.Tests/TestBase.cs
In prep for changes to how we handle subscriptions internally, this does several things:
- Upgrades default Redis server assumption to 3.x
- Routes PING on Subscription keepalives over the subscription bridge appropriately
- Fixes cluster sharding from default(RedisKey) to shared logic for RedisChannel as well (both in byte[] form)
- General code cleanup in the area (getting a lot of DEBUG/VERBOSE noise into isolated files)
=> Pub/Sub: default to 3.0, fix PING, fix server selection in cluster, and cleanup

.github/workflows/CI.yml
We're testing netcoreapp3.1 and net6 now, so no need for the 5.x runtime.
=> Builds: remove .NET 5.0 installer

docs/ReleaseNotes.md, docs/Timeouts.md, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/ExceptionFactory.cs, src/StackExchange.Redis/PerfCounterHelper.cs, tests/StackExchange.Redis.Tests/ExceptionFactoryTests.cs
I swear I already did this somewhere but it got lost, this adds additional thread pool stats exposed in .NET Core 3.1+. We'll get for example `ThreadPool.PendingWorkItemCount` on exception messages to better indicate app contention.
=> Exceptions: Add threadpool stats in .NET Core+

LICENSE, docs/Basics.md, docs/ExecSync.md, docs/KeysValues.md, docs/PipelinesMultiplexers.md, docs/ReleaseNotes.md, docs/Scripting.md, docs/ServerMaintenanceEvent.md, docs/ThreadTheft.md, docs/Transactions.md, docs/index.md, src/StackExchange.Redis/CommandMap.cs, tests/RedisConfigs/3.0.503/redis.windows-service.conf, tests/RedisConfigs/3.0.503/redis.windows.conf
- Code formatting
- http:// -> https://
- Generally updating MDSN links that moved
- Updates moved SSDB site
- Adding Timeouts link (resolves #1942)
Note: touches the license file but only to update to https:// URLs.
=> Migrates links to https:// everywhere possible and misc doc tweaks

Directory.Build.props, docs/ReleaseNotes.md, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/ExceptionFactory.cs, src/StackExchange.Redis/PhysicalConnection.cs, src/StackExchange.Redis/Utils.cs, tests/StackExchange.Redis.Tests/Config.cs, tests/StackExchange.Redis.Tests/ExceptionFactoryTests.cs
This changes the default client name to append "(v2.5.x)" on the end (no spaces because Redis doesn't support spaces in client names). It won't append if someone is setting their client name explicitly in options, only for our default, so should be a safe change.
I'm not sure if a `Utils` class (internal) is best here, but seemed like the right path. I really didn't want to ref version from `ExceptionFactory` in the multiplexer...
=> Client name: append library version suffix

src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/Enums/Proxy.cs, src/StackExchange.Redis/Enums/ServerType.cs, src/StackExchange.Redis/Interfaces/IConnectionMultiplexer.cs, src/StackExchange.Redis/ServerEndPoint.cs
This should make PRs like #1977 and #1425 much easier.
=> Proxy: move to extension methods

docs/ReleaseNotes.md, src/StackExchange.Redis/Message.cs, src/StackExchange.Redis/PhysicalBridge.cs, src/StackExchange.Redis/RedisBatch.cs, src/StackExchange.Redis/RedisTransaction.cs, src/StackExchange.Redis/ResultProcessor.cs, tests/StackExchange.Redis.Tests/ExceptionFactoryTests.cs
There seems to be just 1 case not covered by the `IncludeDetailsInExceptions` option on `ConnectionMultiplexer` - this remedies that. The option is on by default so this shouldn't break people like I thought initially.
Overall, we should probably also move this option to `ConfigurationOptions` and defaults if we do that (#1987).
=> Fix for #1967: Sanitizing message failures

src/StackExchange.Redis/StackExchange.Redis.csproj
This removes the .NET 6 specific build from the main library. In testing many previous performance issues filed around past releases (vs. 1.2.6), I was testing this example:
```cs
using StackExchange.Redis;
using System;
using System.Diagnostics;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
var options = ConfigurationOptions.Parse("localhost,abortConnect=false");
using ConnectionMultiplexer muxer = ConnectionMultiplexer.Connect(options);
var subscriber = muxer.GetSubscriber();
int count = 0;
var sw = Stopwatch.StartNew();
Parallel.For(0, 1000, x =>
{
subscriber.Publish("cache-events:cache-testing", "hey");
Interlocked.Increment(ref count);
});
sw.Stop();
Console.WriteLine($"Total in {sw.ElapsedMilliseconds} ms");
```
This parallel thread contention state is one …
=> Rollback: remove .NET 6 build

tests/StackExchange.Redis.Tests/BacklogTests.cs
Make this a bit more resilient as the cluster changes members from other tests firing in CI.
=> Tests: Improve QueuesAndFlushesAfterReconnectingClusterAsync

docs/ReleaseNotes.md, src/StackExchange.Redis/CommandMap.cs, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/RedisSubscriber.cs, src/StackExchange.Redis/ServerEndPoint.cs, tests/StackExchange.Redis.Tests/Config.cs
In investigating an issue in #1989, I found a few gaps. Overall:
1. Twemproxy has an out of date CommandMap, which propagated to Envoy.
2. We were expecting both interactive and subscription connections to complete to complete the async handler...but we shouldn't because subscriptions may be disabled.
3. RedisSubscriber changes on the sync path weren't validating the message (asserting the command map has it enabled).
This fixes all of the above and adds another test considering all 3.
=> Misc connection/subscription fixes

src/StackExchange.Redis/PhysicalBridge.cs
A few tweaks to the changes #2008 for disposing and normalization.
=> #2008 Follow-ups

src/StackExchange.Redis/ExceptionFactory.cs, src/StackExchange.Redis/PhysicalBridge.cs, tests/StackExchange.Redis.Tests/BasicOps.cs, tests/StackExchange.Redis.Tests/ExceptionFactoryTests.cs, tests/StackExchange.Redis.Tests/PubSubMultiserver.cs
In troubleshooting these 2 tests, I realized what's happening: a really dumb placement mistake in #2008. Now, instead of locking _inside the damn lock_, it loops outside a bit cleaner and higher up. Performance wins are the same but it's a lot sander and doesn't block both the backlog and the writer for another 5 seconds. Now _only_ the thread lingers and it'll try to get the lock when running another pass, if it gets any in the next 5 seconds.
=> Backlog locking fixes - more #2008 follow-up

docs/ReleaseNotes.md, src/StackExchange.Redis/ConnectionMultiplexer.cs, tests/StackExchange.Redis.Tests/ConnectCustomConfig.cs
=> Added CommandMap check before requesting cluster nodes

docs/ReleaseNotes.md, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/ValueStopwatch.cs
This tweaks logging a bit to make it easier to parse and switches timings to `ValueStopwatch` while I'm in here adding one. Helps investigate things like #2017.
=> Connection logging: enhancements!

docs/ReleaseNotes.md, src/StackExchange.Redis/PhysicalBridge.cs, src/StackExchange.Redis/PhysicalConnection.cs, src/StackExchange.Redis/ServerEndPoint.cs
This resolves #1988 by respecting when the `SELECT` command has been disabled. It's memoized which seems  bit extreme here but that's because we're inside the lock and every op matters. Measured locally to ensure no regressions.
=> Fix for #1988 - respect SELECT missing from command map

docs/Configuration.md, docs/ReleaseNotes.md, src/StackExchange.Redis/ConfigurationOptions.cs, src/StackExchange.Redis/PhysicalConnection.cs, tests/StackExchange.Redis.Tests/Config.cs
This adds a new config `Action` that allows modification of a socket after creating it and before connecting. It's passing the endpoint and connection type as well so if necessary per-connection options can be set.
Resolves #1472.
=> Add ConfigurationOptions.BeforeSocketConnect

docs/ReleaseNotes.md, src/StackExchange.Redis/RedisDatabase.cs
Since "XTRIM key MAXLEN 0" is allowed by Redis, it may be useful remove the coded constraint "MAXLEN > 0" in order to clean the whole stream
=> Allow XTRIM maxLength equal 0

.github/.github.csproj, Directory.Build.props, Directory.Build.targets, Directory.Packages.props, StackExchange.Redis.sln, src/Directory.Build.props, tests/BasicTestBaseline/BasicTestBaseline.csproj, tests/ConsoleTestBaseline/ConsoleTestBaseline.csproj, toys/StackExchange.Redis.Server/StackExchange.Redis.Server.csproj, toys/TestConsoleBaseline/TestConsoleBaseline.csproj
This migrates to Directory.Pacakges.props and bumps versions of things we don't want to cause binding redirect pain on.
=> Solution: Centralized package versions and test/toy dependency updates

src/StackExchange.Redis/ConnectionMultiplexer.cs
This option isn't used anymore - nuke it (non-API beak).
=> ConnectionMultiplexer.Factory: cleanup

src/StackExchange.Redis/PhysicalConnection.cs
We log this, but then forgot to abort, woops. Actually bail in this case, no reason to rapidly issue sockets to nowhere.
=> Fix for #1813 - don't actually connect to a null endpoint

docs/ReleaseNotes.md, src/StackExchange.Redis/RedisServer.cs
This is an errant addition to client kill I guess no one tripped on for 8+ years, just happened across it in NRT deep dives.
=> Bug: fix ClientKill/ClientKillAsync when by ClientType

src/StackExchange.Redis/Configuration/DefaultOptionsProvider.cs
Adding a known provider can trigger an iteration race in the GetForEndpoints foreach. Instead of locking everywhere, given the rarity of adding a provider, instead I'm creating a new list and swapping the ref for the next iteration.
=> DefaultOptionsProvider: prevent AddProvider race

src/StackExchange.Redis/RedisFeatures.cs, tests/StackExchange.Redis.Tests/Databases.cs, tests/StackExchange.Redis.Tests/GeoTests.cs, tests/StackExchange.Redis.Tests/Hashes.cs, tests/StackExchange.Redis.Tests/Keys.cs, tests/StackExchange.Redis.Tests/Lists.cs, tests/StackExchange.Redis.Tests/Memory.cs, tests/StackExchange.Redis.Tests/Scans.cs, tests/StackExchange.Redis.Tests/Scripting.cs, tests/StackExchange.Redis.Tests/Sets.cs, tests/StackExchange.Redis.Tests/SortedSets.cs, tests/StackExchange.Redis.Tests/Streams.cs, tests/StackExchange.Redis.Tests/Strings.cs, tests/StackExchange.Redis.Tests/Transactions.cs
This should again make PRs more straightforward by having 1 way to do things, and doesn't leave us appending kind of random surface area to `RedisFeatures`.
Also tidies up a few `RedisFeatures` versions to be what docs reflect.
=> Tests: move to skip by version

docs/ReleaseNotes.md, src/StackExchange.Redis/RedisDatabase.cs
The current implementation of XACK, XCLAIM and XPENDING uses a ComandValuesMessage. Due to this the GetHashSlot() method always returns -1. 
Using these commands in a redis cluster environment will result in MOVED responses as the commands are send to incorrect endpoints.
=> Fix hashslot calculation for XACK, XCLAIM and XPENDING

docs/index.md
Adds a link to fuget.org for people who want to quickly go search/browse the latest package's API.
=> Link to fuget.org on docs site

src/StackExchange.Redis/APITypes/LatencyHistoryEntry.cs, src/StackExchange.Redis/APITypes/LatencyLatestEntry.cs, src/StackExchange.Redis/ClientInfo.cs, src/StackExchange.Redis/ClusterConfiguration.cs, src/StackExchange.Redis/CommandMap.cs, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/Enums/ClientFlags.cs, src/StackExchange.Redis/Enums/RedisType.cs, src/StackExchange.Redis/Enums/SaveType.cs, src/StackExchange.Redis/Format.cs, src/StackExchange.Redis/Interfaces/IDatabase.cs, src/StackExchange.Redis/Interfaces/IDatabaseAsync.cs, src/StackExchange.Redis/Interfaces/IRedis.cs, src/StackExchange.Redis/Interfaces/IRedisAsync.cs, src/StackExchange.Redis/Interfaces/IServer.cs, src/StackExchange.Redis/Interfaces/ISubscriber.cs, src/StackExchange.Redis/Interfaces/ITransaction.cs, src/StackExchange.Redis/Maintenance/AzureMaintenanceEvent.cs, src/StackExchange.Redis/RedisDatabase.cs, src/StackExchange.Redis/RedisFeatures.cs, src/StackExchange.Redis/ResultProcessor.cs, src/StackExchange.Redis/Role.cs, src/StackExchange.Redis/TaskExtensions.cs, src/StackExchange.Redis/ValueStopwatch.cs, tests/StackExchange.Redis.Tests/Hashes.cs, tests/StackExchange.Redis.Tests/PubSub.cs, tests/StackExchange.Redis.Tests/SanityChecks.cs, tests/StackExchange.Redis.Tests/Scans.cs, tests/StackExchange.Redis.Tests/SharedConnectionFixture.cs, tests/StackExchange.Redis.Tests/Strings.cs
This does a few things globally to the interfaces:
- De-dupes `<remarks>` since evidently past the first one doesn't count/render
- Links our redis command links (and all others) so they're easily clickable!
- Moves a few types to proper class files
- In places sync/async methods are adjacent, utilizes `<inheritdoc cref="" /> to de-dupe
- ...and some other misc URL cleanup throughout.
In general: docs only change - I think we should merge this as-is to help PRs coming in, then I'll continue to iterate on docs.
=> Docs: Love! Linking, <remarks> fixes, code formatting, etc.

.github/workflows/CI.yml
See https://github.com/dotnet/runtime/pull/47935 for details, basically enables color output even though console output is redirected for a better time in GitHub actions.
=> Add .NET 6.0 env variable for color output

docs/ReleaseNotes.md, src/StackExchange.Redis/PhysicalConnection.cs
fix #2117
it appears that some of the RESP2 fallback support for client-side caching uses multi-bulk payloads; this currently causes a connection break, so we definitely need to stop *the failure*, but we can also interpret unary arrays similarly to simple values, which should at least allow simple cases to work
=> for pub/sub, treat length-one arrays comparably to simple values

docs/ReleaseNotes.md, src/StackExchange.Redis/ConnectionMultiplexer.Sentinel.cs
In the Sentinel Connection Multiplexer, since `OnManagedConnectionRestored` can be executed on a different thread, it's possible for it to dispose the timer just before `OnManagedConnectionFailed` calls `.Change()` on the timer, which leads to an `ObjectDisposedException` being thrown in `OnManagedConnectionFailed`. Since the connection was restored, it seems safe to suppress these exceptions, instead of requiring locking around the reference to `connection.sentinelPrimaryReconnectTimer`.
=> Fix race condition in Sentinel connection multiplexer

src/StackExchange.Redis/ExceptionFactory.cs, src/StackExchange.Redis/ResultProcessor.cs
`ConnectionMultiplexer.IncludePerformanceCountersInExceptions` is marked for deprecation. This change redirects references to the replacement at `ConfigurationOptions.IncludePerformanceCountersInExceptions`
=> Update IncludePerformanceCountersInExceptions refs to new location

docs/index.md
In the "API Browser" link text, the reference to fuget.org was furget.org. This change is to correct the spelling of the site.
=> fix: corrected fuget.org typo

docs/ReleaseNotes.md, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/Interfaces/IConnectionMultiplexer.cs, src/StackExchange.Redis/PublicAPI.Shipped.txt, src/StackExchange.Redis/PublicAPI.Unshipped.txt, tests/StackExchange.Redis.Tests/SharedConnectionFixture.cs
Fixes #2160.
We may want to implement `IAsyncDisposable` in more public `IDisposable` classes which can dispose their resources asynchronously.
=> Implement IAsyncDisposable from IConnectionMultiplexer

docs/ReleaseNotes.md, src/Directory.Build.props, src/StackExchange.Redis/RedisBase.cs, src/StackExchange.Redis/RedisDatabase.cs, src/StackExchange.Redis/RedisServer.cs, src/StackExchange.Redis/RedisSubscriber.cs
@NickCraver - This will fix #2016 
The issue is that when `GetFeatures` does the server selection, it uses `PING` as the command it's asking about, so when the multiplexer responds with a server, it responds with any server. Of course, then when it goes to execute the command, it's been explicitly handed a server, so it honors that choice but checks it to make sure it's a valid server to send the command to, so if you're executing a write command and `GetFeatuers` just so happened to output a read-only replica, when the multiplexer does the 'is this a valid server?' check, it determines it is not and propagates the error. that's what causes the blowup. By passing in the RedisCommand to `GetFeatures`, we allow it to make an informed choice of server for that Redis Command.
The other option …
=> adding some smarts to GetFeatures

docs/ReleaseNotes.md, src/Directory.Build.props, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/Interfaces/IConnectionMultiplexer.cs, src/StackExchange.Redis/Interfaces/IDatabase.cs, src/StackExchange.Redis/Interfaces/IDatabaseAsync.cs, src/StackExchange.Redis/PublicAPI.Shipped.txt, tests/StackExchange.Redis.Tests/SharedConnectionFixture.cs, tests/StackExchange.Redis.Tests/TestBase.cs
Making things a bit easier for when you need to iterate over servers for a multiplexer
=> Add ConnectionMultiplexer.GetServers() API

Directory.Build.props, docs/ReleaseNotes.md, docs/Timeouts.md, src/StackExchange.Redis/PhysicalConnection.cs
Since we're in a head-of-queue style situation here, the first non-timeout we hit means we're done - hop out and release the lock. Small docs fix tucked in here because reasons.
=> Timeouts: hop out of queue processing as soon as we know no more are eligible for timeout

docs/ReleaseNotes.md, src/StackExchange.Redis/ConnectionMultiplexer.Sentinel.cs, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/EndPointCollection.cs, tests/StackExchange.Redis.Tests/Sentinel.cs
Fixes #2233.
There were 2 issues here contributing:
1. Sentinel was modifying the config options, which we no longer clone. Now, we clone the endpoints and pass them down as explicit overrides into the child connection.
2. EndpointCollection...wasn't actually cloning. I can't believe this didn't show up elsewhere. Collection<T> takes a ref directly without copy of members when forming, so even if ew did clone...we'd be modifying the same thing.
=> Sentinel: fix repeat connects

docs/ReleaseNotes.md, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/RedisLiterals.cs, src/StackExchange.Redis/ResultProcessor.cs, tests/StackExchange.Redis.Tests/Secure.cs
Fixes #1879. In the case where a password is wrong, now indicates "WRONGPASS invalid username-password pair or user is disabled" rather than "NOAUTH Returned - connection has not authenticated" to help users diagnose their problem a bit easier.
=> Auth: Better exception for bad passwords

docs/ReleaseNotes.md, src/StackExchange.Redis/ResultProcessor.cs
ResultProcessor should be more reticent if IncludeDetailInExceptions is disabled
=> Respect IncludeDetailInExceptions in MOVED etc scenarios from ResultProcessor

docs/ReleaseNotes.md, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/ServerEndPoint.cs, src/StackExchange.Redis/StackExchange.Redis.csproj, tests/StackExchange.Redis.Tests/Cluster.cs, tests/StackExchange.Redis.Tests/CommandTimeouts.cs, tests/StackExchange.Redis.Tests/ConnectingFailDetection.cs, tests/StackExchange.Redis.Tests/Failover.cs, tests/StackExchange.Redis.Tests/TestBase.cs
Allegedly fixes https://github.com/StackExchange/StackExchange.Redis/issues/2251 and https://github.com/StackExchange/StackExchange.Redis/issues/2265 but likely introduces all kinds of regressions.
```
19:07:57.0669: Connecting (sync) on .NET 6.0.9 (StackExchange.Redis: v2.6.69.61631)
19:07:57.1215: redis.api.services.revdevs.internal:6380,keepAlive=60,syncTimeout=5000,asyncTimeout=5000,allowAdmin=False,version=2.0,connectTimeout=5000,password=*****,tiebreaker=__Booksleeve_TieBreak,ssl=True,sslHost=localhost,configChannel=__Booksleeve_MasterChanged,abortConnect=False,resolveDns=False,connectRetry=3,proxy=None,configCheckSeconds=60,defaultDatabase=0
19:07:57.1273: redis.api.services.revdevs.internal:6380/Interactive: Connecting...
19:07:57.1402: redis.api.services.revdevs.internal:6380: …
```
=> 2251: Fixes missing activation of the sub leg during initial endpoint discovery

docs/ReleaseNotes.md, src/StackExchange.Redis/ExceptionFactory.cs, src/StackExchange.Redis/PhysicalConnection.cs, tests/StackExchange.Redis.Tests/AsyncTests.cs, tests/StackExchange.Redis.Tests/ExceptionFactoryTests.cs
In a multiplexed setup we often see a timeout _behind_ a large payload in the process of parsing (or not). This is meant to help better diagnose that case, by recording what the last payload size was that came through this connection.
Needs some @mgravell eyes on the record point here and if we want to adjust (or if it's wrong due to buffers in a way I'm not understanding). I realize this won't work on a payload so large enough it blows all buffers completely, but I don't see how to solve that either the way we properly stream parse. I think it'll still improve most cases we see this in.
=> Timeouts: add "last-in" for the last payload's length to exception messages

docs/Configuration.md, docs/ReleaseNotes.md, src/StackExchange.Redis/Configuration/Tunnel.cs, src/StackExchange.Redis/ConfigurationOptions.cs, src/StackExchange.Redis/PhysicalConnection.cs, src/StackExchange.Redis/PublicAPI/PublicAPI.Shipped.txt, src/StackExchange.Redis/PublicAPI/PublicAPI.Unshipped.txt, tests/StackExchange.Redis.Tests/Config.cs, tests/StackExchange.Redis.Tests/HttpTunnelConnect.cs
1. add a tunnel config option, which is used to influence connection creation
2. implement http-tunnel as a well-known tunnel, integrated via the `http:` prefix on the tunnel option
tunnels are implemented as concrete subclasses of the `Tunnel` type; an HTTP proxy "connect" implementation is provided as a well-known version that is supported inside `Parse` - but custom 3rd-party tunnel implementations can also be provided via the object-model (not `Parse`)
A `Tunnel` allows:
- overriding the `EndPoint` used to create `Socket` connections, or to suppress `Socket` creation entirely (by default, the same logical endpoint requested is provided back out)
- provide a "before socket connect" twin (mirrors delegate approach, but: async; by default, do nothing)
- provide a "before authenticate" …
=> Configuration/Connections: Allow HTTP tunneling

docs/ThreadTheft.md
The old wording equated `<httpRuntime targetFramework="4.5" />` to `<add key="aspnet:UseTaskFriendlySynchronizationContext" value="false" />`, when the linked citation makes it clear that the effect is the opposite: `<httpRuntime targetFramework="4.5" />` is inferred as adding the setting `<add key="aspnet:UseTaskFriendlySynchronizationContext" value="true" />`.
> Second, `<httpRuntime targetFramework="4.5" />` is a shortcut that allows the ASP.NET runtime to infer a wide array of configuration settings. If the runtime sees this setting, it will expand it out just as if you had written the following:
> ```
>     ...
>     <add key="aspnet:UseTaskFriendlySynchronizationContext" value="true" />
> ```
https://devblogs.microsoft.com/dotnet/all-about-httpruntime-targetframework/
=> Correction on documented behavior of 'httpRuntime targetFramework="4.5"'

src/StackExchange.Redis/KeyspaceIsolation/BatchWrapper.cs, src/StackExchange.Redis/KeyspaceIsolation/DatabaseExtension.cs, src/StackExchange.Redis/KeyspaceIsolation/KeyPrefixed.cs, src/StackExchange.Redis/KeyspaceIsolation/KeyPrefixedBatch.cs, src/StackExchange.Redis/KeyspaceIsolation/KeyPrefixedDatabase.cs, src/StackExchange.Redis/KeyspaceIsolation/KeyPrefixedTransaction.cs, tests/StackExchange.Redis.Tests/ConfigTests.cs, tests/StackExchange.Redis.Tests/KeyPrefixedBatchTests.cs, tests/StackExchange.Redis.Tests/KeyPrefixedDatabaseTests.cs, tests/StackExchange.Redis.Tests/KeyPrefixedTests.cs, tests/StackExchange.Redis.Tests/KeyPrefixedTransactionTests.cs, tests/StackExchange.Redis.Tests/LockingTests.cs
This renames the various wrappers to IMO more intuitive "KeyPrefixedX" - just couldn't get used to the previous model when touching N files for an API addition, hoping this makes it a little clearer overall, also has the benefit of batching them in UI due to common prefix.
=> Internals Rename: *Wrapper -> "KeyPrefixed"

docs/ReleaseNotes.md, src/StackExchange.Redis/ExceptionFactory.cs, src/StackExchange.Redis/PerfCounterHelper.cs, src/StackExchange.Redis/ResultProcessor.cs, src/StackExchange.Redis/StackExchange.Redis.csproj
The original purpose of this was to get system-level CPU to help advise people filing issues that their machine overall was under too much load and that's why we were seeing timeouts. However, due to ecosystem changes and shifts the actual reporting of this counter has dropped off so dramatically it's not actually doing what it's supposed to be doing and giving us signal data to help.
Given it's a dependency chain that also depends ultimately on some problematic packages now (e.g. System.Drawing.Common) and isn't cross-platform correctly...let's just remove it. It's not a net win anymore.
Fixes #2283.
=> Dependencies: remove System.Diagnostics.PerformanceCounter

docs/ReleaseNotes.md, src/StackExchange.Redis/ConnectionMultiplexer.cs, tests/StackExchange.Redis.Tests/CommandTimeoutTests.cs
Meant to help address #1520, #1660, #2074, and #2020.
I'm not 100% sure about this because if there is a MOVED happening (e.g. bad proxy somewhere) this would just continually re-run...but only once every 5 seconds. Overall though, we linger in a bad state retrying moves until a discovery happens today and this could be resolved much faster.
=> Cluster: Proactively reconfigure when we hit a MOVED response

docs/ReleaseNotes.md, src/StackExchange.Redis/ClusterConfiguration.cs, src/StackExchange.Redis/PublicAPI/PublicAPI.Shipped.txt, tests/StackExchange.Redis.Tests/CommandTimeoutTests.cs, tests/StackExchange.Redis.Tests/ConfigTests.cs
Right now we don't pay attention to fail state (PFAIL == FAIL) and continue trying to connect in the main loop. I don't believe this was intended looking at the code, we just weren't handling the flag appropriately. Added now.
Docs at: https://redis.io/commands/cluster-nodes/
=> Fix #2249: Handle fail on cluster node responses appropriately

docs/ReleaseNotes.md, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/ExceptionFactory.cs, src/StackExchange.Redis/PhysicalBridge.cs, src/StackExchange.Redis/ServerEndPoint.cs, tests/BasicTest/BasicTest.csproj, tests/BasicTestBaseline/BasicTestBaseline.csproj, tests/StackExchange.Redis.Tests/ExceptionFactoryTests.cs, tests/StackExchange.Redis.Tests/SentinelTests.cs, toys/KestrelRedisServer/KestrelRedisServer.csproj, toys/TestConsole/TestConsole.csproj, toys/TestConsoleBaseline/TestConsoleBaseline.csproj
More info to help us advise and debug timeouts for users! 
Overall adds for timeout messages:
- `Sync-Ops`: A count of synchronous operation calls
- `Async-Ops`: A count of asynchronous operation calls
- `Server-Connected-Seconds`: How long the bridge in question has been connected ("n/a" if not connected)
=> Counters: add sync-ops, async-ops, and how long a server has been connected

docs/ReleaseNotes.md, src/StackExchange.Redis/ScriptParameterMapper.cs, tests/StackExchange.Redis.Tests/Helpers/Attributes.cs, tests/StackExchange.Redis.Tests/ScriptingTests.cs
This changes the regex to use `RegexOptions.CultureInvariant` and adds an easy way to do tests like this in the future with `[Fact, TestCulture("tr-TR")]` for example, which will set and restore the culture for a specific test.
Before/after break/fix test included for the Turkish case.
=> LuaScript: use invariant regex on parameter parsing (fixes #2350)

docs/ReleaseNotes.md, src/StackExchange.Redis/ExceptionFactory.cs, tests/StackExchange.Redis.Tests/SecureTests.cs
I improved the auth fail handling/message a while back in #2224, but we should set the `ConnectionFailureType` more specifically as well here so that people can handle it much easier. Fixing!
=> Fix #2362: Set FailureType to AuthenticationFailure for auth exceptions

.github/workflows/CI.yml, Directory.Build.props, StackExchange.Redis.sln, appveyor.yml, docs/ReleaseNotes.md, src/StackExchange.Redis/BufferReader.cs, src/StackExchange.Redis/Format.cs, src/StackExchange.Redis/PhysicalConnection.cs, src/StackExchange.Redis/RawResult.cs, src/StackExchange.Redis/RedisValue.cs, tests/StackExchange.Redis.Tests/FormatTests.cs, tests/StackExchange.Redis.Tests/RedisValueEquivalencyTests.cs, toys/StackExchange.Redis.Server/RedisRequest.cs
fix #2368
- implement Length() for other encodings (using format layout)
- unify format code
- switch to C# 11 for u8 strings (needed a few "scoped" modifiers adding)
- tests for format and Length
=> Implement RedisValue.Length for all underlying storage kinds

docs/ReleaseNotes.md, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/ExtensionMethods.Internal.cs, src/StackExchange.Redis/Message.cs, src/StackExchange.Redis/PhysicalConnection.cs
Deadlock scenario reported with one path (`RecordConnectionFailed`) taking queue then message locks, and another path (`ExecuteSyncImpl`) taking message then queue locks; change *both* paths to only take one lock at a time - never nested.
1. in `RecordConnectionFailed` don't hold the queue lock when we abort things - only hold it when fetching next
2. in `ExecuteSyncImpl`, don't hold the message lock when throwing for timeout
3. to avoid similar not yet seen: in `GetHeadMessages`, don't blindly wait forever on the message lock
also standardise on `TryPeek`/`TryDequeue`
=> fix #2376 - avoid deadlock scenario when completing dead connections

appveyor.yml
The update blog post (https://www.appveyor.com/updates/2023/02/24/) doesn't match the inventory (https://www.appveyor.com/docs/windows-images-software/), primarily: .NET 6 SDK which is LTS is no longer on the 2019 image which seems like an oops. Bypassing the issue for now by getting on the 2022 image.
=> AppVeyor: move to VS 2022 image

docs/ReleaseNotes.md, src/StackExchange.Redis/ChannelMessageQueue.cs, src/StackExchange.Redis/PublicAPI/PublicAPI.Shipped.txt, src/StackExchange.Redis/PublicAPI/PublicAPI.Unshipped.txt, tests/StackExchange.Redis.Tests/PubSubTests.cs
fix #2400
note in particular that we create the queue with multi-reader mode, so there are no unusual concurrency concerns here
=> expose IAsyncEnumerable on ChannelMessageQueue

docs/Configuration.md
Update the 'Configuration' documentation page with the correct default 'ReconnectRetryPolicy' value.
Reference: 
- [src/StackExchange.Redis/ConfigurationOptions.cs](https://github.com/SonnyRR/StackExchange.Redis/blob/improvement/configuration-docs-retry-policy/src/StackExchange.Redis/ConfigurationOptions.cs#L466)
- [src/StackExchange.Redis/Configuration/DefaultOptionsProvider.cs](https://github.com/SonnyRR/StackExchange.Redis/blob/improvement/configuration-docs-retry-policy/src/StackExchange.Redis/Configuration/DefaultOptionsProvider.cs#L152)
=> Reference the correct default retry policy

docs/ReleaseNotes.md, src/StackExchange.Redis/RedisServer.cs, src/StackExchange.Redis/RedisValue.cs, tests/StackExchange.Redis.Tests/Issues/Issue2418.cs
See #2418
(I also looked at custom `==` operators, but that created API ambiguity between `==` on `RedisValue?`, and `null` literals
=> Clarify meaning of RedisValue.IsInteger

docs/ReleaseNotes.md, src/StackExchange.Redis/ChannelMessageQueue.cs, src/StackExchange.Redis/Configuration/DefaultOptionsProvider.cs
- DefaultOptionsProvider.TryGetAzureRoleInstanceIdNoThrow use Type.GetType to check for Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment, so the trimmer knows to preserve this type, if it is in the app
- ChannelMessage use the added public API for ChannelReader CanCount and Count, but fallback to reflection on netcoreapp3.1, since those APIs are not available on that runtime.
Contributes to #2449
This at least removes the warnings from using `Microsoft.Extensions.Caching.StackExchangeRedis`.
We could also add a trimming test app as outlined in https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming#show-all-warnings-with-sample-application, along with a unit test that publishes the app and ensures there are no new warnings. LMK if you think …
=> Fix first round of trim warnings

docs/ReleaseNotes.md, src/StackExchange.Redis/Configuration/DefaultOptionsProvider.cs, src/StackExchange.Redis/PublicAPI/PublicAPI.Shipped.txt, src/StackExchange.Redis/RedisFeatures.cs, src/StackExchange.Redis/RedisLiterals.cs, src/StackExchange.Redis/ServerEndPoint.cs, tests/StackExchange.Redis.Tests/DefaultOptionsTests.cs, tests/StackExchange.Redis.Tests/TestBase.cs
If a wrapper package is generally in use in a deployment, it may want to override what we set as the library name in `CLIENT SETINFO lib-name <name>`. This allows doing so via the `DefaultOptionsProvider` (intentionally not on `ConfigurationOptions` directly as version isn't either).
Note that this does NOT upgrade the test suite to 7.2.0 RC1. I did test and this works, but there are other breaks we need to evaluate - I'll open another PR separately to demonstrate.
=> DefaultOptionsProvider: allow overriding LibName

docs/ReleaseNotes.md, src/StackExchange.Redis/ConfigurationOptions.cs, src/StackExchange.Redis/ConnectionMultiplexer.Sentinel.cs, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/KeyspaceIsolation/KeyPrefixed.cs, src/StackExchange.Redis/Maintenance/AzureMaintenanceEvent.cs, src/StackExchange.Redis/PhysicalBridge.cs, src/StackExchange.Redis/PublicAPI/PublicAPI.Shipped.txt, src/StackExchange.Redis/RedisChannel.cs, src/StackExchange.Redis/ServerEndPoint.cs, tests/ConsoleTest/Program.cs, tests/StackExchange.Redis.Tests/ChannelTests.cs, tests/StackExchange.Redis.Tests/ConfigTests.cs, tests/StackExchange.Redis.Tests/Issues/Issue1101Tests.cs, tests/StackExchange.Redis.Tests/KeyPrefixedDatabaseTests.cs, tests/StackExchange.Redis.Tests/KeyPrefixedTests.cs, tests/StackExchange.Redis.Tests/PreserveOrderTests.cs, tests/StackExchange.Redis.Tests/PubSubCommandTests.cs, tests/StackExchange.Redis.Tests/PubSubMultiserverTests.cs, tests/StackExchange.Redis.Tests/PubSubTests.cs, tests/StackExchange.Redis.Tests/SentinelFailoverTests.cs, tests/StackExchange.Redis.Tests/TestBase.cs
=> mark the implicit RedisChannel operators as [Obsolete]

docs/ReleaseNotes.md, src/StackExchange.Redis/KeyspaceIsolation/KeyPrefixed.cs, src/StackExchange.Redis/PublicAPI/PublicAPI.Shipped.txt, src/StackExchange.Redis/RedisChannel.cs, tests/StackExchange.Redis.Tests/ChannelTests.cs, tests/StackExchange.Redis.Tests/FailoverTests.cs
(also fix some remaining debug tests)
=> naming only: IsPatternBased -> IsPattern

docs/ReleaseNotes.md, src/StackExchange.Redis/ConnectionMultiplexer.Profiling.cs, src/StackExchange.Redis/Interfaces/IConnectionMultiplexer.cs, src/StackExchange.Redis/PublicAPI/PublicAPI.Shipped.txt, tests/StackExchange.Redis.Tests/Helpers/SharedConnectionFixture.cs
RegisterProfiler allows for a null ProfilingSession to be returned - it is even documented with "or returning null to not profile".
Fixing the nullable annotation to indicate that null is an acceptable result of the profilingSessionProvider function.
=> Fix nullability annotation of IConnectionMultiplexer.RegisterProfiler

docs/ReleaseNotes.md, src/StackExchange.Redis/ConnectionMultiplexer.ReaderWriter.cs, src/StackExchange.Redis/PhysicalBridge.cs, src/StackExchange.Redis/StackExchange.Redis.csproj, tests/StackExchange.Redis.Tests/ConfigTests.cs
This allows for using new APIs introduced in net6.0.
In order to enable building for net6.0, we also need to revert the thread pool changes in #1939 and #1950. This was already effectively reverted in #1992 by not building for net6.0. Now that we are building for net6.0 again, these if-defs need to be removed.
Questions:
1. Does this need a ReleaseNotes entry? I don't think there is any user-visible affect to this change.
1. Should `net5.0` be removed? It has been end-of-life for over a year. I left it in, for now. It can be removed in the future, if we think it should be removed.
cc @NickCraver @mgravell
=> Enable net6.0 build

tests/StackExchange.Redis.Tests/Issues/Issue2507.cs, tests/StackExchange.Redis.Tests/StringTests.cs
Fixing the current tests stalling PRs. Issue2507 fundamentally can't play nice either others, especially shared connections and simultaneous, so fixing that case, and adding `SetEmpty`) which has come up a few times as an example of this working.
=> Test: Fix Issue2507 and add String.SetEmpty

Directory.Packages.props, tests/StackExchange.Redis.Tests/KeyPrefixedBatchTests.cs, tests/StackExchange.Redis.Tests/KeyPrefixedDatabaseTests.cs, tests/StackExchange.Redis.Tests/KeyPrefixedTests.cs, tests/StackExchange.Redis.Tests/KeyPrefixedTransactionTests.cs, tests/StackExchange.Redis.Tests/StackExchange.Redis.Tests.csproj
This is a test-only change. I don't want to risk an upgrade and harvesting PII from anyone who works on our project, so I'm removing Moq immediately. See https://github.com/moq/moq/issues/1372 for details/discussion.
=> [Tests] Remove Moq as a dependency

src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/TextWriterLogger.cs
Occasionally we'd see `chunkLength` errors from `StringWriter` `.ToString()` calls after connecting. I think we've isolated this (via test stress runs) down to a write happening post-lock on the `TextWriterLogger` disposal. This lock in dispose ensures we're not trying to write to a writer we should have fully released at the end of a `.Connect()`/`.ConnectAsync()` call.
=> Logging: fix race in disposal of a passed-in TextWriter

docs/Timeouts.md
With this change https://github.com/StackExchange/StackExchange.Redis/pull/2500 active Timers count is now part of the log
=> Documentation: Update Timeouts.md to include new Timers info in the log

tests/StackExchange.Redis.Tests/AbortOnConnectFailTests.cs, tests/StackExchange.Redis.Tests/Helpers/Extensions.cs, tests/StackExchange.Redis.Tests/RoleTests.cs
Fixes:
- `DisconnectAndNoReconnectThrowsConnectionExceptionAsync`: Under load, we're not connecting in 50ms for the initial thing, and stability > speed, so give a little on this test to help out. Average runtime will be higher, but that's way better than sporadically failing.
- `Roles`: Don't assume we're in the initial primary/replica setup (we may have failed over) and make it work either way.
=> Tests: Increase overall stability

src/StackExchange.Redis/Interfaces/IDatabase.cs, src/StackExchange.Redis/Interfaces/IDatabaseAsync.cs
=> Fix HashDelete return value documentation

docs/ReleaseNotes.md, src/StackExchange.Redis/CommandMap.cs, tests/StackExchange.Redis.Tests/SentinelTests.cs
This allows connections through Sentinel via RESP3 by adding `HELLO` to the command map.
Fixes #2591.
=> Sentinel: Add HELLO support

docs/ReleaseNotes.md, src/StackExchange.Redis/PhysicalBridge.cs, src/StackExchange.Redis/PhysicalConnection.cs
In Linux, we see 15 minute socket stalls due to OS-level TCP retries. What this means is the PhysicalConnection detects no issues on the pipe that's retrying, but is also not receiving data at all leading to long stalls in client applications. The goal here is to detect that we're timing out commands people have issued to the connection but we're getting _NOTHING_ back on the socket at all. In this case, we should assume the socket is dead and issue a reconnect so that we get out of the hung situation much faster.
For an initial go at this, we've chosen 4x the timeout interval as a threshold, but could make this configurable if needed.
=> Connections: detect and handle the Linux dead socket case

Directory.Packages.props, docs/ReleaseNotes.md, src/StackExchange.Redis/Hacks.cs, src/StackExchange.Redis/PublicAPI/net6.0/PublicAPI.Shipped.txt, src/StackExchange.Redis/StackExchange.Redis.csproj
fix #2619
as per guidance from the runtime folks, we should declare a type-forward for `IsExternalInit`, so that it gets correctly bound (in particular when netstandard is involved, as the build and execution environments are more likely to differ, leading to modreq confusion)
=> add type-forward on IsExternalInit

docs/ReleaseNotes.md, src/StackExchange.Redis/RedisTransaction.cs, tests/StackExchange.Redis.Tests/TransactionTests.cs
Fixes #2321 
For transactions, if you remove `SELECT` from the command map, it will still try to send one if you issue an unknown/eval/evalsha command - this adds a bit of logic when enqueuing messages to interrogate the multiplexer to see if SELECT is in the command map.
=> Honor select disposition in transactions

docs/ReleaseNotes.md, src/StackExchange.Redis/PhysicalConnection.cs
This adds a bit of null ref handling (few ifs). Fixes #2576.
Overall, this is biting people in the shutdown race, more likely under load, so let's eat the if checks here to prevent it. I decided to go with the specific approach here as to not affect inlining.
=> Fix #2576: PhysicalConnection: Better shutdown handling

docs/ReleaseNotes.md, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/PhysicalConnection.cs, src/StackExchange.Redis/ResultProcessor.cs, src/StackExchange.Redis/ServerEndPoint.cs
1: don't treat trivial clusters as clusters - Alibaba uses this config
2: report synchronous failures immidiately and accurately
fix #2642
For context, Alibaba reports from `cluster nodes` as 2 nodes:
``` txt
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa {proxy endpoint} myself,master - 0 0 0 connected 0-16383
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb {proxy endpoint} slave aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 0 0 0 connected
```
which confuses things somewhat; this isn't a valid/normal cluster configuration, so: ignore it!
Other relevant metadata:
from `config`:
```
databases=256
```
from `info`:
```
cluster_enabled:1
databases:256
nodecount:2
```
=> Support Alibaba pseudo-cluster configurations

docs/ReleaseNotes.md, src/StackExchange.Redis/ServerEndPoint.cs, tests/StackExchange.Redis.Tests/Issues/Issue2653.cs
=> Sanitize client setinfo metadata

docs/ReleaseNotes.md, src/StackExchange.Redis/ConfigurationOptions.cs, tests/StackExchange.Redis.Tests/ConfigTests.cs
release [2.7.23](https://github.com/StackExchange/StackExchange.Redis/releases/tag/2.7.23) added a `ConfigurationOptions.HeartbeatConsistencyChecks` option, but that option is not represented in `Clone()`; fix that
=> Support `HeartbeatConsistencyChecks` in `Clone()`

docs/ReleaseNotes.md
=> Correct link to RespLogging doc

src/StackExchange.Redis/Interfaces/IDatabase.cs, src/StackExchange.Redis/Interfaces/IDatabaseAsync.cs
Closes https://github.com/StackExchange/StackExchange.Redis/issues/2697.
All of the replacements were empirically tested to be correct via simple programs in combination with a local redis instance.
Notably, there is one worrying nit; in testing it turns out that the `IDatabase.List{Left,Right}Pop(RedisKey, long, CommandFlags)` overload which I talked about in the issue _can_ actually return null, contrary to its nullability annotations. This occurs on missing key; in that case redis replies
Nil reply: if the key does not exist.
as per https://redis.io/docs/latest/commands/lpop/, which then at
https://github.com/StackExchange/StackExchange.Redis/blob/cb8b20df0e2975717bde97ce95ac20e8e8353572/src/StackExchange.Redis/ResultProcessor.cs#L1546-L1547
and later at …
=> Replace all occurrences of "nil" in `IDatabase(Async)` xmldoc with less ambiguous alternatives

src/StackExchange.Redis/RedisFeatures.cs, tests/StackExchange.Redis.Tests/StreamTests.cs
Closes/Fixes #2724
no development required , it already works in the same way XREAD with a given id and inherently covers the use of `+` 
just added some test cases to verify.
=> support reading from last message from stream with xread

docs/Configuration.md, src/StackExchange.Redis/Configuration/DefaultOptionsProvider.cs, src/StackExchange.Redis/ConfigurationOptions.cs, src/StackExchange.Redis/Enums/ConnectionFailureType.cs, src/StackExchange.Redis/Message.cs, src/StackExchange.Redis/PhysicalBridge.cs, src/StackExchange.Redis/PhysicalConnection.cs, src/StackExchange.Redis/PublicAPI/PublicAPI.Shipped.txt, src/StackExchange.Redis/PublicAPI/PublicAPI.Unshipped.txt, tests/BasicTest/BasicTest.csproj, tests/BasicTestBaseline/BasicTestBaseline.csproj, tests/ConsoleTest/Program.cs, tests/ConsoleTestBaseline/ConsoleTestBaseline.csproj, tests/StackExchange.Redis.Tests/BasicOpTests.cs, tests/StackExchange.Redis.Tests/ConfigTests.cs, tests/StackExchange.Redis.Tests/ConnectCustomConfigTests.cs, tests/StackExchange.Redis.Tests/ResultBoxTests.cs, tests/StackExchange.Redis.Tests/TestBase.cs
Fixes #2706
This adds additional `ECHO` items after every outbound request, and adds validation of that correlation marker before treating responses as valid.
This is initial draft only; needs conversion to sequence and testing of failure modes.
=> Implement high integrity mode for commands

src/StackExchange.Redis/RedisFeatures.cs, tests/RedisConfigs/Dockerfile
Closes/Fixes #2738 
this is just to move the integration test against to newer version of Redis
=> test against version 7.4-rc1 issue #2738

.github/workflows/CI.yml
docker-compose is not available by default anymore on `ubuntu-latest`
[details here]( https://github.com/actions/runner-images/issues/9692)
=> switch to docker compose

docs/ReleaseNotes.md, src/StackExchange.Redis/PhysicalBridge.cs
This is an issue identified in ##2778 and #2779 where we're not updating replication topology if heartbeat consistency checks are enabled because we exit the `if` structure early. This still runs that check if it's due in both cases, without changing the behavior of the result processor.
=> Fix #2778: Run CheckInfoReplication even with HeartbeatConsistencyChecks

docs/ReleaseNotes.md, src/StackExchange.Redis/CommandMap.cs
Resolves #2793 
Updates Envoyproxy command map according to [Envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/redis)
=> Update command map for Envoy

docs/ReleaseNotes.md, src/StackExchange.Redis/PhysicalBridge.cs
When we have slowly adding things to the heartbeat (originally intended just to send data to keep connections alive) like detecting connection health, the if/else has gotten more complicated. With the addition of `HeartbeatConsistencyChecks`, we prevented some fall throughs to later checks which means that if that option is enabled, we were no longer detecting dead sockets as intended.
This is a tactical fix for the combination, but I think overall we should look at refactoring how this entire method works because shoehorning these things into the original structure/purpose has been problematic several times.
=> Always perform "last read" check in heartbeat when HeartbeatConsistencyChecks is enabled

src/StackExchange.Redis/Format.cs, tests/StackExchange.Redis.Tests/ConnectionFailedErrorsTests.cs, tests/StackExchange.Redis.Tests/FailoverTests.cs, tests/StackExchange.Redis.Tests/FormatTests.cs
=> format ipv6 endpoints correctly

docs/ReleaseNotes.md, src/StackExchange.Redis/Configuration/AzureOptionsProvider.cs, tests/StackExchange.Redis.Tests/ConfigTests.cs, tests/StackExchange.Redis.Tests/DefaultOptionsTests.cs
Detect when connecting to a new Azure Managed Redis cache, and adjust default connection settings to align with their capabilities. 
More about Azure Managed Redis: https://learn.microsoft.com/azure/azure-cache-for-redis/managed-redis/managed-redis-overview
=> Automatically detect and tune for Azure Managed Redis caches

docs/ReleaseNotes.md, src/StackExchange.Redis/CommandMap.cs
Fix #2823 in combination with https://github.com/envoyproxy/envoy/pull/37620
Note that in passing it occurs that this is an exclusion list, and these exclusions have not been kept up-to-date with new command additions; consequently, the exclusion lists may be incomplete in a few cases. This isn't a *huge* problem - the command will still fail, but it will fail at the proxy or server instead of at the client.
=> update envoy defs to allow `UNWATCH`

README.md
=> Improve readme - what even is this?

src/StackExchange.Redis/PhysicalConnection.cs
Fixes #2652
Previously, `RecordQuit` only recorded a client-initiated `QUIT` if `_ioPipe` was a `SocketConnection`, which is not true when using SSL.
Since there is a 1-1 relationship between `PhysicalConnection` and `_ioPipe`, store whether the client initiated the shutdown on the `PhysicalConnection` object instead of (only) delegating it to `SocketConnection`.
The line `var pipe = connectingPipe ?? _ioPipe` seems irrelevant to this PR because `connectingPipe` is only set once, in `ConnectedAsync`, and would be relevant only if an exception were thrown between when `pipe` is set and when its value is assigned to `_ioPipe` (i.e., between lines 1612-15).
=> Track client-initiated shutdown for any pipe type

docs/ReleaseNotes.md, src/StackExchange.Redis/PhysicalBridge.cs, tests/StackExchange.Redis.Tests/ConnectingFailDetectionTests.cs
Additional case handling for #2853, respecting backoff in the disconnected -> resurrecting state case. We need to check backoff in that flow as well to prevent a premature `TryConnect`.
=> Fix: Rexpect backoff in the disconnect -> resurrection case as well

src/StackExchange.Redis/ConnectionMultiplexer.Sentinel.cs, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/ExceptionFactory.cs, src/StackExchange.Redis/PhysicalBridge.cs
Multiplexer reconfiguration (e.g., caused by AzureMaintenance) is an important event and as such should be logged.
Additionally, include connection name in exception when applicable (PhysicalBridge).
=> Log multiplexer reconfiguration

docs/ReleaseNotes.md, src/StackExchange.Redis/ConfigurationOptions.cs, src/StackExchange.Redis/PhysicalConnection.cs, src/StackExchange.Redis/PublicAPI/PublicAPI.Shipped.txt, src/StackExchange.Redis/PublicAPI/net6.0/PublicAPI.Shipped.txt, src/StackExchange.Redis/PublicAPI/net8.0/PublicAPI.Shipped.txt
Historically, certs only worked with PFX files, which made it a pain to work with the cert pairs typically downloaded from hosts like Redis Ltd; however, on more recent .NET versions PEM is fully available. Here, we:
- add new methods on `ConfigurationOptions` (akin to the existing `TrustIssuer` method) to configure certificates from files
- support PEM in the ambient setup
There are no tests added here, due to the inherent problems of CI talking to such servers; however:
``` c#
var options = ConfigurationOptions.Parse("redis-redacted.redislabs.com:4242"); // port also redacted
options.TrustIssuer(@"C:\Code\RedisKeys\redis_ca.pem");
options.SetUserPemCertificate(@"C:\Code\RedisKeys\redis-redacted.crt", @"C:\Code\RedisKeys\redis-redacted.key");
using var conn = await …
```
=> Make it easier to use user certificate files

docs/ReleaseNotes.md, src/StackExchange.Redis/Configuration/LoggingTunnel.cs, src/StackExchange.Redis/ExtensionMethods.cs, src/StackExchange.Redis/PhysicalConnection.cs
Previously when supporting earlier versions of .NET Framework, we did not have an async version of `AuthenticateAsClient` due to socket itself not having async handlers in earlier versions of `netstandard`. These days though with the supported target framework matrix, this can be fully async to prevent thread starvation specifically in the case where we're able to connect a socket but the server is overwhelmed and unable to finish TLS negotiations.
Example:
This is a case we've never seen stall before, where the server is able to accept connections but unable to complete TLS negotiation, so there's never been a reported stall raising this potential issue. Last night we saw it live on a major instance though. It's still TBD how this was manifesting server-side (could be a proxy stall in …
=> Connections: Move all AuthenticateAsClient to async

src/StackExchange.Redis/README.md, src/StackExchange.Redis/StackExchange.Redis.csproj
links are intentionally duplicated; IIRC the release notes MD processor is fairly restricted
=> add package README.md to make NuGet happier

.github/workflows/CI.yml, tests/RedisConfigs/.docker/Redis/Dockerfile
This PR is to update the _Redis_ versions running in the CI, there are two different test setups according to environments, one on _Ubuntu_ and the other on _Windows_;
- _Ubuntu_ job is now using docker image with latest _Redis_ release, it was using a relatively up-to-date version (**7.4-rc1 -> 7.4.2**)
-  _Windows_ job was using the binaries of an old version of _Redis_ which was build to run on _Windows_ env, but it is quite old(**Redis 3.0.503**) and lack of a set of features/changes that _StackExchange.Redis_ already capable of when running with up-to-date _Redis_ versions. So this is replaced with the **Redis 7.4.2** which is the latest GA Release(as of now) in package repository. 
Setup for _Windows_  essentially leverages [wsl setup](https://github.com/Vampire/setup-wsl) on …
=> Use up-to-date releases of Redis for CI workflow 

docs/ReleaseNotes.md, docs/Timeouts.md, src/StackExchange.Redis/ClientInfo.cs, src/StackExchange.Redis/CommandMap.cs, src/StackExchange.Redis/Enums/RedisCommand.cs, src/StackExchange.Redis/Interfaces/ISubscriber.cs, src/StackExchange.Redis/Message.cs, src/StackExchange.Redis/PhysicalBridge.cs, src/StackExchange.Redis/PhysicalConnection.cs, src/StackExchange.Redis/PublicAPI/PublicAPI.Shipped.txt, src/StackExchange.Redis/RawResult.cs, src/StackExchange.Redis/RedisChannel.cs, src/StackExchange.Redis/RedisDatabase.cs, src/StackExchange.Redis/RedisFeatures.cs, src/StackExchange.Redis/RedisSubscriber.cs, src/StackExchange.Redis/ResultProcessor.cs, src/StackExchange.Redis/ServerEndPoint.cs, tests/StackExchange.Redis.Tests/ClusterTests.cs, toys/StackExchange.Redis.Server/RedisRequest.cs, toys/StackExchange.Redis.Server/RedisServer.cs
Continuation of https://github.com/StackExchange/StackExchange.Redis/pull/2498/
=> Support sharded pubsub commands

.github/workflows/CI.yml, Directory.Packages.props, StackExchange.Redis.sln, appveyor.yml, docs/ReleaseNotes.md, src/StackExchange.Redis/Interfaces/IServer.cs, src/StackExchange.Redis/KeyspaceIsolation/KeyPrefixed.cs, src/StackExchange.Redis/KeyspaceIsolation/KeyPrefixedDatabase.cs, src/StackExchange.Redis/LuaScript.cs, src/StackExchange.Redis/PhysicalConnection.cs, src/StackExchange.Redis/ResultProcessor.cs, src/StackExchange.Redis/ServerEndPoint.cs, src/StackExchange.Redis/StackExchange.Redis.csproj, src/StackExchange.Redis/TextWriterLogger.cs, tests/StackExchange.Redis.Tests/KeyPrefixedDatabaseTests.cs, tests/StackExchange.Redis.Tests/KeyPrefixedTests.cs, tests/StackExchange.Redis.Tests/LockingTests.cs, tests/StackExchange.Redis.Tests/LoggerTests.cs, tests/StackExchange.Redis.Tests/RespProtocolTests.cs, tests/StackExchange.Redis.Tests/ScriptingTests.cs, tests/StackExchange.Redis.Tests/SortedSetTests.cs
also deals with some non-functional IDE QOL improvements due to VS->Rider migration, aka "make the robots stop screaming at me"
=> (code-rot) Update package dependencies

StackExchange.Redis.sln, docs/AsyncTimeouts.md, docs/docs.csproj, docs/index.md, tests/StackExchange.Redis.Tests/CancellationTests.cs
- add guidance on using inbuilt framework methods for async timeout/cancellation
- (admin) migrate docs to csproj to avoid sln overhead
Intentionally no release-notes delta here; not part of "release"
=> docs: offer guidance on using framework methods for async timeouts / cancellation

src/StackExchange.Redis/ConnectionMultiplexer.cs
related #2899
Adopts source-generated LoggerMessage for all logging calls, replacing direct string interpolation and formatting in log messages. Introduces strongly-typed helper structs for efficient log value formatting and factors out complex ToString() calls.
Improves logging performance, ensures consistency across log entries, and reduces unnecessary allocations by deferring message formatting until required. Lays groundwork for easier log message maintenance and better structured logging.
=> Replaces inline logging with source-generated LoggerMessage

src/StackExchange.Redis/LoggerExtensions.cs, src/StackExchange.Redis/ServerEndPoint.cs
related #2899 
Migrates Redis server endpoint logging from string interpolation to LoggerMessage attributes for better performance and structured logging support.
Adds 14 new LoggerMessage methods for server connection lifecycle events including handshake, authentication, configuration, and buffer operations.
Uses ServerEndPointLogValue wrapper to ensure consistent server representation in logs while maintaining type safety.
github-copilot prompt used:
=> chore: Replaces string interpolation with structured logging - ServerEndPoint

src/StackExchange.Redis/LoggerExtensions.cs, src/StackExchange.Redis/ResultProcessor.cs
related to #2899
Replaces manual string interpolation with compile-time generated LoggerMessage methods for better performance and structured logging.
Adds 16 new LoggerMessage extension methods covering response logging and auto-configuration scenarios for Redis server connections.
Improves logging efficiency by eliminating runtime string formatting overhead and enables better log analysis through consistent message templates.
satisfying!
https://github.com/user-attachments/assets/788c563f-9f63-430c-a88a-40b0f7dc812a
=> chore: Replaces string interpolation with structured logging - ResultProcessor

src/StackExchange.Redis/ConnectionMultiplexer.Sentinel.cs, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/EndPointCollection.cs, src/StackExchange.Redis/LoggerExtensions.cs
closes #2899
Converts manual log message formatting to LoggerMessage source generator methods for better performance and structured logging support.
Improves logging efficiency by eliminating string allocations when logging is disabled and provides consistent structured data for log analysis tools.
=> chore: Replaces string interpolation with structured logging - left overs

docs/ReleaseNotes.md, src/StackExchange.Redis/Format.cs, src/StackExchange.Redis/PhysicalConnection.cs, src/StackExchange.Redis/RedisValue.cs, tests/StackExchange.Redis.Tests/KeyAndValueTests.cs, tests/StackExchange.Redis.Tests/RedisValueEquivalencyTests.cs
by using `double : IUtf8Formattable`
open question: this is net8+; however, for anything netcoreapp2.1+ we could actually use the `Span<char>` overload to a scratch buffer, which would avoid a `string` alloc (and copy down if needed, like we do today from `string`). However, this would only really impact net6 which is EOL, so I do *not* propose to introduce extra code for that.
This PR also fixes a pre-existing oddity where, (as `RedisValue`):
- `"na" != "NA"`
- `"nan" == "NAN"`
- `"nand" != "NAND"`
(and similar for `inf`)
=> Improve `double` formatting performance on net8+ and fix equality incorrectness re special doubles

.editorconfig, tests/BasicTest/Program.cs, tests/StackExchange.Redis.Benchmarks/SlowConfig.cs, tests/StackExchange.Redis.Tests/ConfigTests.cs, tests/StackExchange.Redis.Tests/LoggerTests.cs, tests/StackExchange.Redis.Tests/ParseTests.cs, tests/StackExchange.Redis.Tests/ProfilingTests.cs
As requested in https://github.com/StackExchange/StackExchange.Redis/pull/2915#issuecomment-3205190140
=> Enable CA1852 and fix warnings for it

src/StackExchange.Redis/ConnectionMultiplexer.Debug.cs, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/PhysicalBridge.cs, src/StackExchange.Redis/PhysicalConnection.cs, src/StackExchange.Redis/Profiling/ProfilingSession.cs, src/StackExchange.Redis/ServerEndPoint.cs, tests/StackExchange.Redis.Tests/FailoverTests.cs, tests/StackExchange.Redis.Tests/PubSubTests.cs, tests/StackExchange.Redis.Tests/SyncContextTests.cs
Thread.VolatileRead is considered legacy; this PR is mostly to remove delta in the RESPite work
=> eng: prefer Volatile.Read over Thread.VolatileRead

docs/ReleaseNotes.md, src/StackExchange.Redis/Message.cs, src/StackExchange.Redis/PublicAPI/PublicAPI.Shipped.txt, src/StackExchange.Redis/PublicAPI/PublicAPI.Unshipped.txt, src/StackExchange.Redis/RedisChannel.cs, src/StackExchange.Redis/RedisDatabase.cs, src/StackExchange.Redis/RedisSubscriber.cs, src/StackExchange.Redis/ServerSelectionStrategy.cs, tests/StackExchange.Redis.Tests/ClusterTests.cs
mitigate #2955
Reason for revert: many environments use very few channels, which can lead to a massively skewed subscriber distribution in cluster scenarios, rather than making good use of the horizontal broadcast feature
- by default: use round-robin (not channel-routing) for "non-sharded" pub/sub
- add new API for channel-routed literals/wildcards
- when publishing, if we're also subscribed: use that connection
- randomize where the round-robin starts, to better randomize startup behaviour
=> Channel routing: revert non-S routing to random, with new API to opt into routed

docs/ReleaseNotes.md, src/StackExchange.Redis/StackExchange.Redis.csproj, toys/StackExchange.Redis.Server/StackExchange.Redis.Server.csproj
fix #2961
problem: linux build does not strong-sign (or rather: it public-signs, which is like delay-sign but: looser)
The cause is explicit in the csproj; this was [added 7 years ago](https://github.com/StackExchange/StackExchange.Redis/commit/f1003b471d82adf527aa7736834e4425b02f8394#diff-15df3c28997ba29023c38391cdb263eab4c5e7c50efc5f2591ac985aeaea5bc2R12); I *assume* this was due to a glitch in .NET Core 2.x (as-was at the time), on non-Windows, but: checking locally: it works fine now
``` txt
> sn -v bin/Release/net8.0/StackExchange.Redis.dll
Mono StrongName - version 6.12.0.199
StrongName utility for signing assemblies
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.
Assembly bin/Release/net8.0/StackExchange.Redis.dll is strongnamed.
```
=> eng: remove PublicSign windows-only restriction

.github/workflows/CI.yml
This is on the way to removing AppVeyor (currently broken) from our environment. Publishes to MyGet when building from a push to main, _not_ on pull requests.
=> Actions: support publishing to MyGet off main branch
