StackExchange.Redis/StackExchange/Redis/SocketManager.cs
Fixing NotImplementedException under Mono while preserving dynamic host name resolution.
=> A fix for https://github.com/StackExchange/StackExchange.Redis/issues/20

StackExchange.Redis/StackExchange/Redis/RedisDatabase.cs
it is ok for When.Always but it must be boolean when using When.NotExists, so change to ResultProcessor.Boolean
=> KeyRename return boolean

StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs
When clients have a burst of IO operations, the thread pool will scale slowly after it hits the minIoThreads.  This can lead to timeouts on clients that are not related to any issues on the network or on the server.  Logging these details will help identify such issues without having to use a debugger to see the state of the thread pool.
=> Add ThreadPool statistics to Timeout message to help debug IOCP issues

StackExchange.Redis.Tests/Issues/Issue182.cs, StackExchange.Redis.Tests/StackExchange.Redis.Tests.csproj
Tested with local Redis 2.8.19 64bit on Windows 7
=> Test case for issue #182

StackExchange.Redis/StackExchange.Redis.StrongName.csproj, StackExchange.Redis/StackExchange.Redis.csproj, StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs, StackExchange.Redis/StackExchange/Redis/IConnectionMultiplexer.cs, StackExchange.Redis_Net40/StackExchange.Redis_Net40.StrongName.csproj, StackExchange.Redis_Net40/StackExchange.Redis_Net40.csproj
=> added IConnectionMultiplexer interface to facilitate better unit testing

StackExchange.Redis.Tests/Transactions.cs, StackExchange.Redis/StackExchange/Redis/Condition.cs
I came across the need to run a transaction only if the first item in a list is an expected value. As suggested in the documentation, I've added some extra conditions for transactions to handle list values.
This adds conditions for whether a list index exists, whether it's equal to an expected value, and the reverse (index does not exist, or is not a specified value). Index can be zero-based (from the start of the list) or negative (from the end of the list).
Includes unit tests to verify the various combinations. Tested on Windows 7, all passed successfully.
=> Add Transaction Conditions for List Index

StackExchange.Redis.Tests/TestBase.cs
Test-only change.  Some exceptions are caught and ignored in synchronous version. On CoreClr with the introduction of NetworkStream.ReadAsync(), they are no longer caught.  This change ignores them so the tests are not marked as failures due to unobserved ambient exceptions.
@mgravell
=> Ignore certain unobserved Task exceptions in test teardown

global.json
It is a minor update but so it is bound to the latest version of the coreclr
=> updated to coreclr version 1.0.0-rc1-update1

Docs/Docs.csproj, Docs/Timeouts.md, StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs
=> proposing timeout error with help link to help customers do an initial troubleshooting

StackExchange.Redis.Tests/DatabaseWrapperTests.cs, StackExchange.Redis.Tests/Issues/SO23949477.cs, StackExchange.Redis.Tests/WrapperBaseTests.cs, StackExchange.Redis/StackExchange/Redis/IDatabase.cs, StackExchange.Redis/StackExchange/Redis/IDatabaseAsync.cs, StackExchange.Redis/StackExchange/Redis/KeyspaceIsolation/DatabaseWrapper.cs, StackExchange.Redis/StackExchange/Redis/KeyspaceIsolation/WrapperBase.cs, StackExchange.Redis/StackExchange/Redis/RedisDatabase.cs
This is my first time looking at SE.Redis source code. Please let me know if I'm off base here.
And... before this is really considered ready for merge-- how do you run the unit tests?
=> Added "When" parameter to SortedSetAdd to support NX and XX options

StackExchange.Redis/StackExchange/Redis/SocketManager.cs
Fix for https://github.com/StackExchange/StackExchange.Redis/issues/582
*Note: verified fix in AWS lambda*
=> Suppress platform check failure on connect

StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs, StackExchange.Redis/StackExchange/Redis/ExceptionFactory.cs, StackExchange.Redis/StackExchange/Redis/PhysicalBridge.cs
=>  AbortOnConnectFailure message in unabletoconnect exception if AbortOnConnectFailure is set

NRediSearch/Query.cs, NRediSearch/Schema.cs
Minor improvements based on #645  recommendations.
=> Feature- NRediSearch Sorting Functionality

monobuild.bash, monobuild.cmd
=> use roslyn csc compiler on mono for C#7 support

.gitignore, StackExchange.Redis.Tests/GeoTests.cs
GeoTests.cs converted to UTF-8, .idea dir added to .gitignore.
=> Rider friendly solution.

docs/Timeouts.md
It threw us a bit when we saw this exception but not the same information :)
=> Added a note on .NET Core and thread counts

StackExchange.Redis.Tests/Booksleeve/Hashes.cs, StackExchange.Redis.Tests/Booksleeve/PubSub.cs, StackExchange.Redis.Tests/Booksleeve/Strings.cs, StackExchange.Redis/StackExchange/Redis/Bitwise.cs, StackExchange.Redis/StackExchange/Redis/ClusterConfiguration.cs, StackExchange.Redis/StackExchange/Redis/CommandMap.cs, StackExchange.Redis/StackExchange/Redis/CommandTrace.cs, StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs, StackExchange.Redis/StackExchange/Redis/DebuggingAids.cs, StackExchange.Redis/StackExchange/Redis/IDatabaseAsync.cs, StackExchange.Redis/StackExchange/Redis/IRedis.cs, StackExchange.Redis/StackExchange/Redis/IRedisAsync.cs, StackExchange.Redis/StackExchange/Redis/IServer.cs, StackExchange.Redis/StackExchange/Redis/ISubscriber.cs, StackExchange.Redis/StackExchange/Redis/ITransaction.cs, StackExchange.Redis/StackExchange/Redis/LuaScript.cs, StackExchange.Redis/StackExchange/Redis/RedisType.cs, StackExchange.Redis/StackExchange/Redis/SaveType.cs, StackExchange.Redis/StackExchange/Redis/SocketManager.cs, StackExchange.Redis/StackExchange/Redis/TaskSource.cs
Except for redisearch.io and www.ideawu.com, because they don't have an https endpoint atm.
=> http -> https for links in codebase.

NRediSearch/Client.cs
An option to disable Stop-Words completely while creating schema.
=> Disable Stop-Words added

StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs, StackExchange.Redis/StackExchange/Redis/Interfaces/IConnectionMultiplexer.cs, StackExchange.Redis/StackExchange/Redis/PhysicalBridge.cs, StackExchange.Redis/StackExchange/Redis/ServerEndPoint.cs
…ing to establish a connection.
This is to assist with issue reported: #783
I'm not sure on best approach to write unit tests for this particular issue - if you have pointers, let me know and I'll happily add them in.
(This was previously submitted #786, but now updated to fix line ending probs).
=> Isconnecting

StackExchange.Redis/StackExchange/Redis/PhysicalConnection.cs
=> Don't log details in Exception thrown by PhysicalConnection unless `IncludeDetailInExceptions` is true.

docs/Basics.md
Fix indentation level on a nested list.
=> Fix indentation on Basics.md

StackExchange.Redis.Tests/PubSub.cs, StackExchange.Redis/ConnectionMultiplexer.cs, StackExchange.Redis/ExceptionFactory.cs, StackExchange.Redis/PhysicalConnection.cs, StackExchange.Redis/RedisBase.cs
Note: this doesn't include command and key, which is still behind the IncludeDetailInExceptions flag
=> Exceptions: add timeout info everywhere

StackExchange.Redis.Tests/DatabaseWrapperTests.cs, StackExchange.Redis.Tests/WrapperBaseTests.cs, StackExchange.Redis/StackExchange/Redis/Interfaces/IDatabase.cs, StackExchange.Redis/StackExchange/Redis/Interfaces/IDatabaseAsync.cs, StackExchange.Redis/StackExchange/Redis/KeyspaceIsolation/DatabaseWrapper.cs, StackExchange.Redis/StackExchange/Redis/KeyspaceIsolation/WrapperBase.cs, StackExchange.Redis/StackExchange/Redis/RedisDatabase.cs
https://redis.io/commands/spop
=> Support count argument in SPOP

tests/StackExchange.Redis.Tests/Streams.cs
Fix for #1027 
From the XREADGROUP docs on [redis.io](https://redis.io/commands/xreadgroup):
> The ID to specify in the STREAMS option when using XREADGROUP can be one of the following two:
> The special > ID, which means that the consumer want to receive only messages that were never delivered to any other consumer. It just means, give me new messages.
Any other ID, that is, 0 or any other valid ID or incomplete ID (just the millisecond time part), will have the effect of returning entries that are pending for the consumer sending the command. **So basically if the ID is not >, then the command will just let the client access its pending entries: delivered to it, but not yet acknowledged.**
Do you think there's a need to improve the `StreamReadGroup` method signatures to make this change …
=> Fix streams consumer group tests.

docs/Basics.md, docs/Configuration.md, docs/KeysScan.md, docs/KeysValues.md, docs/PipelinesMultiplexers.md, docs/Profiling_v1.md, docs/Profiling_v2.md, docs/PubSubOrder.md, docs/Transactions.md, toys/StackExchange.Redis.Server/readme.md
Made markdown files more readable in Visual Studios by changing code highlighting
=> Made markdown files more readable in Visual Studios

src/StackExchange.Redis/CommandMap.cs
=> Add shutdown command to sentinel command map.

docs/Timeouts.md
sorry just noiticed this as well
=> typo and reference to wrong parameter (I think)

docs/Timeouts.md
=> Added Backlog-writer

src/StackExchange.Redis/StreamEntry.cs, tests/StackExchange.Redis.Tests/Streams.cs
API proposal for #1359; greatly simplifies field access
=> Add indexer (get) to `StreamEntry`

src/NRediSearch/Client.cs, src/NRediSearch/Document.cs, src/NRediSearch/Query.cs, src/NRediSearch/SearchResult.cs, tests/NRediSearch.Test/ExampleUsage.cs, tests/NRediSearch.Test/QueryTest.cs
#1251 
[Scoring in RediSearch](https://oss.redislabs.com/redisearch/Scoring.html)
Allow to set scoring (pre-bundled scoring function)
=> Scoring in RediSearch

src/StackExchange.Redis/RedisResult.cs, tests/StackExchange.Redis.Tests/Scripting.cs
Fixes null ref possibility from `RedisResult`
=> Fix conversions from null RedisResult

Directory.Build.props, docs/ReleaseNotes.md, version.json
This bumps versioning for the 2.1.0 release, ready to GA!
=> 2.1.0 Release!

.github/.github.csproj, .github/workflows/Linux.yml, StackExchange.Redis.sln, tests/RedisConfigs/Dockerfile, tests/StackExchange.Redis.Tests/Failover.cs
Billing issues have cleared on the org - taking a stab at this.
First attempt: let's get a Linux CI going.
=> Actions! Let's see if we can make this merry-go-round spin.

Directory.Build.props, Directory.Build.targets, Packages.props, StackExchange.Redis.sln, global.json, tests/NRediSearch.Test/NRediSearch.Test.csproj, tests/StackExchange.Redis.Tests/StackExchange.Redis.Tests.csproj
=> fix build to get green shields for Source Link and Deterministic

src/StackExchange.Redis/Profiling/ProfiledCommand.cs
See [ValueStopwatch.cs](https://github.com/dotnet/runtime/blob/master/src/libraries/Common/src/Extensions/ValueStopwatch/ValueStopwatch.cs#L36)
=> Fix more than 99 times of elapsed time on Linux

docs/Configuration.md
=> Obsolete label for responseTimeout and writeBuffer in docs

src/StackExchange.Redis/Interfaces/IDatabase.cs, src/StackExchange.Redis/Interfaces/IDatabaseAsync.cs
=> Fixed a copy/paste mistake in documentation

src/StackExchange.Redis/ConfigurationOptions.cs, tests/StackExchange.Redis.Tests/Config.cs
xref #883 (in particular [this comment](https://github.com/StackExchange/StackExchange.Redis/issues/883#issuecomment-679844312))
=> improve error message when reporting config string errors

src/StackExchange.Redis/ConnectionMultiplexer.cs
=> Don't set a default serverselection stratergy in case there was a fault getting the servertype

src/StackExchange.Redis/Interfaces/IDatabase.cs, src/StackExchange.Redis/Interfaces/IDatabaseAsync.cs, src/StackExchange.Redis/KeyspaceIsolation/DatabaseWrapper.cs, src/StackExchange.Redis/KeyspaceIsolation/WrapperBase.cs, src/StackExchange.Redis/RedisDatabase.cs, tests/StackExchange.Redis.Tests/DatabaseWrapperTests.cs, tests/StackExchange.Redis.Tests/Lists.cs, tests/StackExchange.Redis.Tests/WrapperBaseTests.cs
Issue: https://github.com/StackExchange/StackExchange.Redis/issues/1450
Add methods for rpushx/lpushx with multiple values
Do not delete old to save backward compatibility
=> Implement api for rpushx/lpushx with multiple values

src/StackExchange.Redis/ConnectionMultiplexer.cs
=> Throw RedisConnectionException instead of NotImplementedException if sentinel entered TILT mode

src/StackExchange.Redis/CommandBytes.cs, tests/StackExchange.Redis.Tests/Commands.cs
(tempted to burn this type completely, but: keep it for now)
fixes #1692
=> increase CommandBytes limit

docs/Timeouts.md
=> Changed a word

src/StackExchange.Redis/Message.cs, src/StackExchange.Redis/PhysicalConnection.cs, src/StackExchange.Redis/RedisBase.cs, src/StackExchange.Redis/RedisDatabase.cs, src/StackExchange.Redis/RedisServer.cs
De-duping for #1759 solution here. These are tweaks from @TimLovellSmith's branch, getting 'em to get noise out of the race stuff.
=> Exception and code cleanup

src/StackExchange.Redis/ResultProcessor.cs
This will help us in debugging what command is trying to be sent in the failure.
=> Redis: add command attempted to NOAUTH results

src/StackExchange.Redis/ConnectionMultiplexer.cs
FWLIW. Not really a hot path, but why not save some electrons.
=> Micro optimization - repeated dictionary lookups

.github/workflows/CI.yml
Adding the test results as a step in GitHub actions for better visibility.
=> Test results in GitHub Actions, we hope

docs/ReleaseNotes.md
For PR: https://github.com/StackExchange/StackExchange.Redis/pull/1684
=> Add release note for replica refresh fix

src/StackExchange.Redis/SocketManager.cs, tests/BasicTest/Program.cs
Making analyzers happy, but teensy perf so why not.
=> Dispose/Finalizers: Cleanup

docs/Scripting.md
See https://github.com/StackExchange/StackExchange.Redis/issues/1371
and
https://github.com/StackExchange/StackExchange.Redis/issues/1246
=> Script transmission in the scripting doku

docs/ReleaseNotes.md, src/NRediSearch/Client.cs
fix .ctor break (avoid MME)
fix "filed" typo (except for .ctor break)
=> fix breaking changes in NRediSearch

src/StackExchange.Redis/ExponentialRetry.cs
=> ExponentialRetry - Comment typos

docs/ReleaseNotes.md, src/StackExchange.Redis/Enums/RedisCommand.cs, src/StackExchange.Redis/Interfaces/IDatabase.cs, src/StackExchange.Redis/Interfaces/IDatabaseAsync.cs, src/StackExchange.Redis/KeyspaceIsolation/DatabaseWrapper.cs, src/StackExchange.Redis/KeyspaceIsolation/WrapperBase.cs, src/StackExchange.Redis/Message.cs, src/StackExchange.Redis/RedisDatabase.cs, src/StackExchange.Redis/RedisFeatures.cs, tests/StackExchange.Redis.Tests/DatabaseWrapperTests.cs, tests/StackExchange.Redis.Tests/Strings.cs, tests/StackExchange.Redis.Tests/WrapperBaseTests.cs
=> Add support for GETDEL command

toys/KestrelRedisServer/KestrelRedisServer.csproj, toys/KestrelRedisServer/Program.cs, toys/KestrelRedisServer/Startup.cs, toys/TestConsole/TestConsole.csproj, toys/TestConsoleBaseline/TestConsoleBaseline.csproj
=> Brings toys up to date to eliminate netcoreapp2.1 errors.

src/StackExchange.Redis/Interfaces/IDatabase.cs
Change result type/value in the documentation for the method `HashSet`: `1` => `True` and `0` => `False`
=> Change result type/value in the xml tag of the method documentation

src/StackExchange.Redis/BufferReader.cs
=> investigate SnapshotPosition error

tests/StackExchange.Redis.Tests/Strings.cs
Can't repro this locally, adding to test suite.
=> Add test for #1578

tests/StackExchange.Redis.Tests/ConnectToUnexistingHost.cs, tests/StackExchange.Redis.Tests/ConnectingFailDetection.cs, tests/StackExchange.Redis.Tests/ExceptionFactoryTests.cs, tests/StackExchange.Redis.Tests/TestBase.cs
Reducing diff from #1912 on bits we can simplify & merge in sooner.
=> Changes for #1912

Directory.Build.targets, docs/ReleaseNotes.md
Pulling this in separately from #1912 as a minimal PR.
=> Update libs: pulling in the disposed Arena fix from Pipelines.Unofficial

src/StackExchange.Redis/ClientInfo.cs, src/StackExchange.Redis/Enums/ClientFlags.cs
This adds the Redis 6.0+ flags from #1912
=> Support latest ClientFlags

docs/Configuration.md, docs/ReleaseNotes.md
This is a pass at updating the docs for the 2.5 prerelease - thoughts?
=> v2.5: Docs!

tests/StackExchange.Redis.Tests/EnvoyTests.cs
This should make AppVeyor a bit friendlier.
=> Envoy: Handle both failure race errors

StackExchange.Redis.sln, tests/ConsoleTest/ConsoleTest.csproj, tests/ConsoleTest/Program.cs, tests/ConsoleTestBaseline/ConsoleTestBaseline.csproj
This adds some console tests for performance work.
=> Adds ConsoleTest/Baseline for some heavier benchmarks

src/StackExchange.Redis/ConfigurationOptions.cs, src/StackExchange.Redis/ConnectionMultiplexer.Compat.cs, src/StackExchange.Redis/ConnectionMultiplexer.Debug.cs, src/StackExchange.Redis/ConnectionMultiplexer.Events.cs, src/StackExchange.Redis/ConnectionMultiplexer.ExportConfiguration.cs, src/StackExchange.Redis/ConnectionMultiplexer.FeatureFlags.cs, src/StackExchange.Redis/ConnectionMultiplexer.Profiling.cs, src/StackExchange.Redis/ConnectionMultiplexer.ReaderWriter.cs, src/StackExchange.Redis/ConnectionMultiplexer.Sentinel.cs, src/StackExchange.Redis/ConnectionMultiplexer.StormLog.cs, src/StackExchange.Redis/ConnectionMultiplexer.Threading.cs, src/StackExchange.Redis/ConnectionMultiplexer.Verbose.cs, src/StackExchange.Redis/ConnectionMultiplexer.cs, src/StackExchange.Redis/EndPointCollection.cs, src/StackExchange.Redis/Maintenance/ServerMaintenanceEvent.cs, src/StackExchange.Redis/PublicAPI.Shipped.txt, src/StackExchange.Redis/ServerSelectionStrategy.cs, src/StackExchange.Redis/WriteResult.cs, tests/StackExchange.Redis.Tests/SSL.cs, tests/StackExchange.Redis.Tests/SharedConnectionFixture.cs
Cleaning up a bit before moving to no-clone for adjustable configuration. No functionality changes, just moving and ordering lots of cheese to make things easier, same with NRT diffs later.
=> ConfigurationOptions: shuffle in prep for no-clone

src/StackExchange.Redis/Interfaces/IServer.cs, src/StackExchange.Redis/Profiling/ProfiledCommand.cs, src/StackExchange.Redis/RedisServer.cs, src/StackExchange.Redis/ResultProcessor.cs, tests/StackExchange.Redis.Tests/Helpers/redis-sharp.cs
Removes the #regions that divide us! (I couldn't find an .editorconfig for this, but removing from existing codebase helps makes it clear for future PRs!)
=> Cleanup: removing evil

src/StackExchange.Redis/Enums/ExpireWhen.cs, src/StackExchange.Redis/Enums/ListSide.cs, src/StackExchange.Redis/Enums/Proxy.cs, src/StackExchange.Redis/Enums/ServerType.cs, src/StackExchange.Redis/Enums/SetOperation.cs, src/StackExchange.Redis/Enums/SortedSetOrder.cs, src/StackExchange.Redis/ExtensionMethods.Internal.cs, src/StackExchange.Redis/Interfaces/IServer.cs, src/StackExchange.Redis/TaskExtensions.cs, src/StackExchange.Redis/TaskSource.cs
This isn't a visibility change, just making public members of internal classes internal themselves to be clearer.
Note: no public API changes in this...so loving that analyzer right now :)
=> Extensions: make internals...internal

tests/StackExchange.Redis.Tests/Expiry.cs
https://github.com/StackExchange/StackExchange.Redis/runs/6199961801?check_suite_focus=true
=> Expiry.TestExpiryOptions FAILED (might be flaky)

.github/workflows/CI.yml, Directory.Packages.props
Upgrading this for some goodies - see https://twitter.com/Tyrrrz/status/1516371034999504897
=> Builds: GitHub Actions logger upgrade

docs/Configuration.md, docs/Server.md
This adds a bit of info on required command permissions to connect.
=> Docs: improvement for #2103 & #1795

docs/ReleaseNotes.md, src/StackExchange.Redis/SocketManager.cs
Follow-up to #900, trying to fix this a bit cleaner for dual IPv4/v6 DNS scenarios (the overload docs point to this solution).
=> Fix for #2240

docs/Configuration.md
Fixes #1419 - adding brief descriptions for primary `SocketManager` options.
=> Docs: add SocketManager

docs/ReleaseNotes.md, src/StackExchange.Redis/ServerSelectionStrategy.cs
note our test suite doesn't cover envoy, so no explicit tests
=> Fix #2426 - don't restrict multi-slot operations on envoy proxy

docs/ReleaseNotes.md
=> Update ReleaseNotes for #2456

.devcontainer/Dockerfile, docs/ReleaseNotes.md, src/StackExchange.Redis/APITypes/StreamGroupInfo.cs, src/StackExchange.Redis/PublicAPI/PublicAPI.Shipped.txt, src/StackExchange.Redis/ResultProcessor.cs, tests/StackExchange.Redis.Tests/StreamTests.cs
=> add StreamGroupInfo EntriesRead and Lag

src/StackExchange.Redis/RawResult.cs
- satisfy infosec scanner that we're not risking pointer wierdness (although in reality, this is always UTF8; can't be hijacked)
- prefer EncodingExtensions.GetString when it is available
- switch payload to an explicit field so we can use ^^^ via pass-by-ref
There is no actual infosec here; if the inbuilt UTF8 implementation is broken, we're already hosed; there is no extension point to replace UTF8
=> Satisfy pointer arithmetic check

Directory.Build.props, docs/ReleaseNotes.md, src/StackExchange.Redis/StackExchange.Redis.csproj
https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#internalsvisibleto
=> Simplify InternalsVisibleTo

docs/ReleaseNotes.md
=> docs: fix a PR link
